<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_submitEmployee</name>
   <tag></tag>
   <elementGuidId>4a934706-5bee-40b3-9c06-3cbc33caa99c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-12.mb-2.d-flex.ng-star-inserted > button.btn.btn-primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c3c4923-8f94-4528-a113-a327b24f812a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b5065ec1-e904-48c0-80f5-3e89226a4fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>e039cae8-5fe1-4941-ae25-593b71deff3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> إضافة </value>
      <webElementGuid>4a600dec-3fb1-4939-8bd0-6c3d17c0d293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-3&quot;)/app-dialog-container[@class=&quot;ng-tns-c40-184 ng-trigger ng-trigger-dialogContainer ng-star-inserted rounded shadow&quot;]/app-employee-form-popup[@class=&quot;fullscreen dialog-item ng-star-inserted&quot;]/div[@class=&quot;dialog-content no-fixed-height&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 mb-2 d-flex ng-star-inserted&quot;]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>417f5545-b4e2-4cde-87aa-934147fac8f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>7ddba96c-18f4-4b07-b97c-ac3f2b88e0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[20]/button</value>
      <webElementGuid>2d6617ce-12e1-4d90-ab04-890a04b8885e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تاريخ انتهاء العقد'])[1]/following::button[1]</value>
      <webElementGuid>20d444b5-fef6-4696-8c83-8dbce7ecc20a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تاريخ انتهاء العمل'])[1]/following::button[1]</value>
      <webElementGuid>56ed7602-0e2b-49d5-9bde-b7714d0295fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إعادة تعيين'])[2]/preceding::button[1]</value>
      <webElementGuid>cfd35a79-6fb6-4b32-8825-ac3240698afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مسح الكل'])[1]/preceding::button[2]</value>
      <webElementGuid>4aebd0a7-6ccf-4ece-8015-130a3369b58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='إضافة']/parent::*</value>
      <webElementGuid>01c3b9b3-9f61-4d5e-8fcc-e48561e67878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/button</value>
      <webElementGuid>a8c82a00-d24f-4c96-bad0-4294a8732c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' إضافة ' or . = ' إضافة ')]</value>
      <webElementGuid>b0167600-02f8-4255-851b-64d6a355d009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
