<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__contractExpiryDate</name>
   <tag></tag>
   <elementGuidId>7dfc91ed-9385-4921-8163-b8fae05efb67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contractExpiryDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contractExpiryDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>24ae5dde-a1bc-4a24-8aa9-60ea92968bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contractExpiryDate</value>
      <webElementGuid>0d2ffdf3-06e6-4f58-863b-22c128022814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contractExpiryDate</value>
      <webElementGuid>573cf7a0-40b5-45ac-ae3b-3584a5c4f4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>contractExpiryDate</value>
      <webElementGuid>45516bac-d860-4534-a913-87895ea347ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b28e63d6-474d-47bd-9197-d5ce137fadb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contractExpiryDate&quot;)</value>
      <webElementGuid>30f3c8b5-6f84-4981-9b0b-db034f4ae607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='contractExpiryDate']</value>
      <webElementGuid>b4af21ae-6748-463b-b1c8-01b4f8eb1e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[19]/div/div</value>
      <webElementGuid>54132e85-9b72-4436-907d-e08711ba6d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div</value>
      <webElementGuid>eb7b0cc2-65fa-454c-a8d0-cd29799a8af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'contractExpiryDate']</value>
      <webElementGuid>e5c61322-181c-4891-9721-c396040e928b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
