<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__ExpIdPass</name>
   <tag></tag>
   <elementGuidId>0cb5621f-1efe-407f-840e-02eeb06a9cac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div/div[3]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ExpIdPass</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa8850ad-661b-47d0-ad86-b2f087bcdb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>ExpIdPass</value>
      <webElementGuid>9e8b4c13-bc8f-406e-bd6b-8c0ba9693fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExpIdPass</value>
      <webElementGuid>7935513a-dd49-4efc-a30a-2156285ea2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>ExpIdPass</value>
      <webElementGuid>54ba5457-20db-463f-abf8-cb67281e68d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c75d1c79-05d4-44ea-a060-46d7094420ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExpIdPass&quot;)</value>
      <webElementGuid>d6888fbc-0791-4a7c-8361-b56b560dba61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ExpIdPass']</value>
      <webElementGuid>0336179f-f28a-42f1-a476-9fc405ffb605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[3]/div/div</value>
      <webElementGuid>03ca19ec-34c3-4f50-8bf7-12c524bc84ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/div/div</value>
      <webElementGuid>68489c22-666f-463e-9ad2-bb07ef7c0d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ExpIdPass']</value>
      <webElementGuid>8642bded-2ca3-4cbe-ab0b-b749e6591d37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
