<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__workStartDate</name>
   <tag></tag>
   <elementGuidId>f85d9a79-4bb7-4df8-8730-3d09024bc883</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workStartDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='workStartDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40b1ad04-9a15-4975-8f1c-c50f9dc48007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>workStartDate</value>
      <webElementGuid>95be0cfc-3254-4645-92bc-6d59d33407d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workStartDate</value>
      <webElementGuid>f34926f9-54d5-4c76-976a-c4357e52b7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>workStartDate</value>
      <webElementGuid>d929cc43-b2f3-4657-b060-fe18f316b177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6d61a1ba-ec0c-4794-ae31-ff9faa7e5ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workStartDate&quot;)</value>
      <webElementGuid>d23481a5-a146-42fb-8196-94a815064e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='workStartDate']</value>
      <webElementGuid>a971d0c5-20f2-491c-839b-9525c9cec124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[17]/div/div</value>
      <webElementGuid>8122c79c-26ab-4aa0-8be0-87ec31b135dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div</value>
      <webElementGuid>fbf3d499-9e06-4aae-a697-9e6c5ddf4b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'workStartDate']</value>
      <webElementGuid>f5cde659-0d74-4e69-bde6-e3a6652a2b53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
