<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__addNewEmployee (plus icon)</name>
   <tag></tag>
   <elementGuidId>9abd0f87-19d5-4d4f-85a8-e880b18abf88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-plus-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-list-1-content']/tab[2]/div/div/div/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d98599b7-a54f-49ed-918b-b2c1ddeed5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-plus-box</value>
      <webElementGuid>c81c0779-6aa9-4ff5-8f5d-404ccda94f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c131-178 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c131-178 ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-12 mb-2 d-flex justify-content-between align-items-end ng-star-inserted&quot;]/div[1]/button[@class=&quot;btn btn-link outline-none d-flex align-items-center&quot;]/i[@class=&quot;mdi mdi-plus-box&quot;]</value>
      <webElementGuid>3867c3a7-c561-489f-96c1-06792d60be9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/div/div/div/button/i</value>
      <webElementGuid>d052893f-8401-4436-8f8f-24283ee44ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[2]/div/div/div/div/button/i</value>
      <webElementGuid>0fb93e4a-c02e-4155-850f-ae81cca0bd53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
