<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__englishName</name>
   <tag></tag>
   <elementGuidId>4760be43-2665-49a0-80d2-ca43fa08ce18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#englishName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='englishName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1c6ea94-58f2-4d8d-8ad2-70fb9d8e2ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>2eabf5ac-8a2d-45d7-b390-29aec8817484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>4ba901ca-bd8a-4433-b76f-bc73f8293f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>48a3fa01-8521-4393-8fc7-e3239039d6ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3a76baab-9ba5-4cfa-9595-74d4c72532d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;englishName&quot;)</value>
      <webElementGuid>949aa4b0-18d3-4dce-90b1-21ee23638ec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='englishName']</value>
      <webElementGuid>18655e42-715b-4b73-9ad9-4b15d2e39569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[3]/input</value>
      <webElementGuid>3f001377-72a2-48a9-8113-15c08382d86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/input</value>
      <webElementGuid>49ad4162-d624-4e68-848d-9f2ff8a9150d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'englishName']</value>
      <webElementGuid>21e165d6-024b-482b-95dc-b3b20be2d7ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
