<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__identificationNumber(update)</name>
   <tag></tag>
   <elementGuidId>4f6b49b6-7eb7-4d7f-a929-2395ffe81c70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identificationNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identificationNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cf0637e-f2e8-4df2-b0cd-3e3da2231bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>a46b3740-55ef-46ed-9ccb-3f53ea9547d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab85e44c-4b5c-4168-afb7-4f344a8a3f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>a790f24c-7143-4c72-b54b-d72b4f546c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c46c3eff-cc52-4051-a6b5-4fc2dbb81f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identificationNumber&quot;)</value>
      <webElementGuid>4b804d05-8551-452f-98a8-a5fdea5cf3e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identificationNumber']</value>
      <webElementGuid>e5a75dbb-c42d-4f91-9fea-aed356c8b18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/div/div/form/div[2]/div/input</value>
      <webElementGuid>2d8c15c1-c6dc-4a59-9641-931df395b944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم التعريف'])[1]/following::input[1]</value>
      <webElementGuid>595baf6a-6ae4-4dae-bea1-6190ca2bd99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم جواز السفر'])[1]/following::input[2]</value>
      <webElementGuid>734a022c-3e56-47ef-8658-aaa9bcc15776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاسم بالعربية'])[1]/preceding::input[1]</value>
      <webElementGuid>7a8caf0f-3bc1-4947-90cb-0b34555a0f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الإسم بالانجليزي'])[1]/preceding::input[1]</value>
      <webElementGuid>226461d9-4622-4cc1-b777-339ed7420583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/input</value>
      <webElementGuid>bbfdcaf1-87fc-456b-a523-480a2a39cd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'identificationNumber']</value>
      <webElementGuid>20b0937c-03ec-40ac-af82-281392ed21e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
