<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__contractLocation</name>
   <tag></tag>
   <elementGuidId>386548f6-0d68-4424-9983-7e17bee6913d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contractLocation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contractLocation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cbf4a40-51d1-445a-a982-76b4d7df270a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contractLocation</value>
      <webElementGuid>42f6197a-926a-4e4d-8ce0-ecc107faacaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>contractLocation</value>
      <webElementGuid>f0e69cc2-b496-44d4-9e9d-bfea767077bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>contractLocation</value>
      <webElementGuid>b674d457-2ba3-4488-bf52-476cb61e2421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2f3e9197-675f-48a0-924d-f50b039ce116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contractLocation&quot;)</value>
      <webElementGuid>0d8937f5-b656-4e5c-a4d4-9376a4a3d501</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contractLocation']</value>
      <webElementGuid>4f4bd2fc-891a-42b8-a5f8-dd9a95c84130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[13]/input</value>
      <webElementGuid>2cce3a46-051b-47f2-bf4d-1af97b4b8b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/input</value>
      <webElementGuid>90618548-be88-495b-8eb9-d718cef94882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contractLocation']</value>
      <webElementGuid>934b82c4-249f-4cbf-ab4f-e5497f064169</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
