<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__passportNumber(update)</name>
   <tag></tag>
   <elementGuidId>878d8e37-65f7-4390-afca-36b9a59cb78b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passportNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passportNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81b25e31-bd3e-46de-866a-382302b3eed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>c010b517-d75c-48d9-893e-975512a49dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da72faab-87fb-4c63-9b63-182bb79cc848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>df32db68-ed55-43ea-bf79-c573afd9f6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e40e0bb3-52b4-45e0-8ebe-5a46562752fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passportNumber&quot;)</value>
      <webElementGuid>08a72814-8e83-4d44-9e4c-0614cf7615cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passportNumber']</value>
      <webElementGuid>42f374e5-1184-4236-9b23-1bd6fc1a4465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/div/div/form/div/div/input</value>
      <webElementGuid>e61a1150-7059-4e36-8194-a1681f5bc3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم جواز السفر'])[1]/following::input[1]</value>
      <webElementGuid>f9877f72-83d8-41f5-a8be-536c12c930e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تفاصيل الموظفين'])[1]/following::input[1]</value>
      <webElementGuid>79e3682f-a22a-4a5a-b2d1-3aee9211a89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم التعريف'])[1]/preceding::input[1]</value>
      <webElementGuid>48c003d9-efa2-46e2-9d8e-fe65035918b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاسم بالعربية'])[1]/preceding::input[2]</value>
      <webElementGuid>be3c8668-147a-412f-af6b-9b199d682844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>4d4c23fd-2ecd-46e4-9d59-2d119dd9dff1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'passportNumber']</value>
      <webElementGuid>ff782855-5efa-4eb7-a6c3-04eb92335203</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
