<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__passportNumber</name>
   <tag></tag>
   <elementGuidId>afb61080-9744-42ff-b9c3-9b0ce9fd173e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6.col-md-4.mb-4.position-relative.ng-star-inserted > #passportNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='passportNumber'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fd522d8-01db-4ea0-b305-dd8ae5cac033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>afacfa0d-fa6e-45f8-8f0b-110f9808f08d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>93778f54-2e53-4b11-b0ca-7787146816a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>9295d731-536d-465d-979a-88af0ddfdf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>4fc8f24e-e7aa-4247-be0f-ea822cd72394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-3&quot;)/app-dialog-container[@class=&quot;ng-tns-c40-184 ng-trigger ng-trigger-dialogContainer ng-star-inserted rounded shadow&quot;]/app-employee-form-popup[@class=&quot;fullscreen dialog-item ng-star-inserted&quot;]/div[@class=&quot;dialog-content no-fixed-height&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-md-4 mb-4 position-relative ng-star-inserted&quot;]/input[@id=&quot;passportNumber&quot;]</value>
      <webElementGuid>333eb59f-1762-4a2e-8af1-9ae116cabef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='passportNumber'])[2]</value>
      <webElementGuid>6f2f8d60-9748-4bab-85d9-dedc19bf6f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[2]/input</value>
      <webElementGuid>96adb6db-7cfa-47dd-ae5f-2e5529d42249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/input</value>
      <webElementGuid>eb64246f-6956-4587-afa9-5065cba5306e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'passportNumber']</value>
      <webElementGuid>37070b16-9602-417f-adf4-927a9b8d5b3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
