<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__identificationNumber</name>
   <tag></tag>
   <elementGuidId>6263c469-3635-4a47-a1e2-0e28338bc85e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-6.col-md-4.mb-4.position-relative.ng-star-inserted > #identificationNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='identificationNumber'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e15ec94a-0ce2-4863-9558-beaa0978aa30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>7be07859-1a6d-42ef-9066-a0834d6619a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>196528a9-de1d-4e60-afce-66fa9d941871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>c087f2fc-c9b6-46f0-8b66-d5b835dbeba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>97020178-fbc5-4940-a921-c2f4943cf27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-3&quot;)/app-dialog-container[@class=&quot;ng-tns-c40-184 ng-trigger ng-trigger-dialogContainer ng-star-inserted rounded shadow&quot;]/app-employee-form-popup[@class=&quot;fullscreen dialog-item ng-star-inserted&quot;]/div[@class=&quot;dialog-content no-fixed-height&quot;]/form[@class=&quot;ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-md-4 mb-4 position-relative ng-star-inserted&quot;]/input[@id=&quot;identificationNumber&quot;]</value>
      <webElementGuid>43ff860c-dab4-4bab-b531-8dd5cff8e04c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='identificationNumber'])[2]</value>
      <webElementGuid>a4fd8a3b-bb35-4ad7-a609-88e418242884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[2]/input</value>
      <webElementGuid>9a21b65c-18d4-4b0f-9729-a66b326761f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/input</value>
      <webElementGuid>74ba0ee9-f91d-41a5-9f0c-7c45493cd944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'identificationNumber']</value>
      <webElementGuid>b188d9c9-4094-4bdb-8a4d-0c48bc6222ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
