<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__arabicName</name>
   <tag></tag>
   <elementGuidId>5f4b2077-977f-4160-89af-7253b588bdfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arabicName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='arabicName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65c19459-d30a-40a3-966d-0b35c71384b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arabicName</value>
      <webElementGuid>9101d231-7cb9-48f6-9dd9-2507dec298d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>arabicName</value>
      <webElementGuid>3c6e3cde-9729-4693-bf4f-3faead48f65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>arabicName</value>
      <webElementGuid>a864f447-c93b-4c34-901b-317630d00727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>05096b27-7425-43fb-96aa-60523564d287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arabicName&quot;)</value>
      <webElementGuid>73304025-a749-40c3-8f0f-c321e2bc95f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='arabicName']</value>
      <webElementGuid>a3c20a0c-3f49-474d-b8eb-adde9b5c926d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[2]/input</value>
      <webElementGuid>476640e5-fb75-4c99-9e26-c493678a3168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/input</value>
      <webElementGuid>bb6b3a79-a59d-4ee1-9abb-b1ea43983158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'arabicName']</value>
      <webElementGuid>ef745503-fdec-4611-b9d8-8b28a80deef1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
