<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jobNumber</name>
   <tag></tag>
   <elementGuidId>51f66a36-f30d-4209-8005-2e603c1bf37e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7aa51c2-fefe-4543-9902-f8cd0023a102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobNumber</value>
      <webElementGuid>5aa03dc9-a9ba-476e-8e36-78eed94b8bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>jobNumber</value>
      <webElementGuid>139e648c-b920-4803-9e50-5eaddcaec72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>jobNumber</value>
      <webElementGuid>221e1e5c-d7d1-4791-8f95-38f24a2df703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3bc1cb94-c508-4a67-8f32-30bf129d5512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobNumber&quot;)</value>
      <webElementGuid>35c17dea-da9e-4d25-bbfb-cb1ff1ce88a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobNumber']</value>
      <webElementGuid>5bb8d0f6-5fc3-4305-8f4f-a89881b012f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-1']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[9]/input</value>
      <webElementGuid>555d9a64-e895-4e78-8aa3-e66797b1d725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>2ea35be5-f513-451e-8681-3ff1c844d1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jobNumber']</value>
      <webElementGuid>ea531723-8692-4edc-9d8c-3b981ebc941c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
