<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mark_Employment</name>
   <tag></tag>
   <elementGuidId>1c569dc0-d101-4443-995e-910a0c00ba68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-item-list']/app-sidebar-menu-item-list/ul/li/app-sidebar-menu-item-list/ul/li/a[2]/span/mark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mark</value>
      <webElementGuid>58d91f13-bc59-49f3-8291-366b62bccca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>طلبات التوظيف</value>
      <webElementGuid>17442f5b-a34f-4263-a272-0f8877ad298b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-list&quot;)/app-sidebar-menu-item-list[@class=&quot;ng-tns-c81-2 ng-tns-c80-3 ng-star-inserted&quot;]/ul[@class=&quot;ng-tns-c80-3 level-1 sidebar-menu-list&quot;]/li[@class=&quot;sidebar-menu-item ng-tns-c80-3 parent-menu-item has-children ng-trigger ng-trigger-expendCollapse ng-star-inserted&quot;]/app-sidebar-menu-item-list[@class=&quot;ng-tns-c80-173 ng-tns-c80-3 ng-star-inserted&quot;]/ul[@class=&quot;ng-tns-c80-173 level-2 sidebar-menu-list&quot;]/li[@class=&quot;sidebar-menu-item ng-tns-c80-173 px-2 ng-trigger ng-trigger-expendCollapse ng-star-inserted&quot;]/a[@class=&quot;d-flex flex-row align-items-center overflow-hidden ng-tns-c80-173 px-2 justify-content-start&quot;]/span[@class=&quot;flex-grow-1 sidebar-menu-item-text text-truncate ng-tns-c80-173&quot;]/mark[1]</value>
      <webElementGuid>d305498f-8ba7-4055-b68f-400f5d6b548e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-item-list']/app-sidebar-menu-item-list/ul/li/app-sidebar-menu-item-list/ul/li/a[2]/span/mark</value>
      <webElementGuid>f7266f4f-d399-4e3f-aebc-cb9492f47b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خدمات عامة'])[1]/following::mark[1]</value>
      <webElementGuid>71157355-0d31-497e-b9e8-2565bfaf4a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الخدمات الالكترونية'])[2]/following::mark[1]</value>
      <webElementGuid>d5dd906d-72cc-49de-b99c-25b4ccaf5e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بريد المستخدم'])[1]/preceding::mark[1]</value>
      <webElementGuid>c3de56e7-429a-4d88-b63b-b427adbdde11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بريد المجموعة'])[1]/preceding::mark[1]</value>
      <webElementGuid>4387235b-953d-431e-8f97-5013cf85ddc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='طلبات التوظيف']/parent::*</value>
      <webElementGuid>0e5567d4-45c0-402b-96d7-757b908370fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mark</value>
      <webElementGuid>d791db8a-9899-42b7-9fa8-4bfee695ecae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mark[(text() = 'طلبات التوظيف' or . = 'طلبات التوظيف')]</value>
      <webElementGuid>71b6cd71-e790-47d5-9016-6f284d91af9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
