<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DatePickerDay</name>
   <tag></tag>
   <elementGuidId>d0222cc9-7589-4410-8d3c-fe4d5e47346a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.myDpDayValue.myDpMarkCurrDay.myDpHighlight</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;d_3_6&quot;)/span[@class=&quot;myDpDayValue myDpMarkCurrDay myDpHighlight&quot;][count(. | //span[@class = 'myDpDayValue myDpMarkCurrDay myDpHighlight']) = count(//span[@class = 'myDpDayValue myDpMarkCurrDay myDpHighlight'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='d_3_6']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dfaf5489-f7d8-4d68-beba-ebcfc7a96393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>myDpDayValue myDpMarkCurrDay myDpHighlight</value>
      <webElementGuid>d45202de-243d-429d-b0b3-9a4caabb5a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sunday, February 26, 2023</value>
      <webElementGuid>ca217cd5-cea6-4bdf-8316-3c78a34553c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>96004afd-2685-4fae-8ac6-14ed465a13d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d_3_6&quot;)/span[@class=&quot;myDpDayValue myDpMarkCurrDay myDpHighlight&quot;]</value>
      <webElementGuid>395819c9-8bdb-4a8a-8448-d708eb5846cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='d_3_6']/span</value>
      <webElementGuid>57907827-a51a-40dc-9199-7ea8264164c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/following::span[28]</value>
      <webElementGuid>2ebab26a-5f6e-4c71-ae5f-29e0cf464b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::span[28]</value>
      <webElementGuid>0b71e52d-5abc-47f8-b1f5-156d85d4c5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حقل مطلوب'])[15]/preceding::span[15]</value>
      <webElementGuid>2ae61fb8-4b7e-487c-92f6-378db88c63eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تاريخ انتهاء العمل'])[1]/preceding::span[16]</value>
      <webElementGuid>bfb3546a-c597-4f0a-b262-26cd4730e254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='26']/parent::*</value>
      <webElementGuid>60e50a49-d351-43ed-8095-1103c2528946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[7]/span</value>
      <webElementGuid>3c2a99e4-9a53-4dfb-9db9-e76e2c6a93da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '26' or . = '26')]</value>
      <webElementGuid>5efb3313-9e83-4f45-99aa-579a9b16cabd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
