<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_CalendarDay</name>
   <tag></tag>
   <elementGuidId>d5c97304-5295-4d02-aaaf-0fa4ac3758f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#d_1_0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//td[@tabindex = '0' and (text() = '${GlobalVariable.CalendarDay}' or . = '${GlobalVariable.CalendarDay}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='d_1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5d28a2d3-7299-4f38-9db9-f333ced8a802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d_1_0 myDpDaycell ng-star-inserted myDpCurrMonth myDpTableSingleDay</value>
      <webElementGuid>9507e167-1253-47b5-a31a-ef73c957696f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d_1_0</value>
      <webElementGuid>048dc80a-059f-442b-b2ae-eba8cbb37360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>897dfa6d-4f7c-48b4-92c0-cad5367be363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.CalendarDay}</value>
      <webElementGuid>8dc9d353-0161-4314-ac4f-a2703363cc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d_1_0&quot;)</value>
      <webElementGuid>62bc50f7-6804-483b-a409-0a81c346fe69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='d_1_0']</value>
      <webElementGuid>f2c38600-ac7f-405d-8bd6-2654502826ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[3]/div/lib-angular-mydatepicker-calendar/div/div/lib-day-view/table/tbody/tr[2]/td</value>
      <webElementGuid>f9629d92-d266-4515-8557-a32ef6ea7099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/following::td[8]</value>
      <webElementGuid>5337c1cb-9c3d-44dc-a168-b845ea7ab69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::td[8]</value>
      <webElementGuid>fb665c3a-6077-4437-ba85-ce535be4e327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حقل مطلوب'])[2]/preceding::td[35]</value>
      <webElementGuid>1b2ae30a-97c7-49e3-8fc8-a51d401674ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lib-day-view/table/tbody/tr[2]/td</value>
      <webElementGuid>047ddeac-7a98-45b4-859e-86081b9dd42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'd_1_0' and (text() = '6' or . = '6')]</value>
      <webElementGuid>78643e67-6309-45c7-a673-79511497261d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
