<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_TomorrowDay</name>
   <tag></tag>
   <elementGuidId>daf73446-a69a-47a8-baf2-171e8e08bc02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='d_1_0']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//td[@tabindex = '0' and (text() = '${GlobalVariable.TomorrowDay}' or . = '${GlobalVariable.TomorrowDay}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#d_1_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f5642232-12af-4165-96af-5a8d0b5d1834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d_1_0 myDpDaycell ng-star-inserted myDpCurrMonth myDpTableSingleDay</value>
      <webElementGuid>67fe657b-781c-453f-a28f-95bff7a50d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d_1_0</value>
      <webElementGuid>ba5a5d8f-1b8c-4453-98ad-3a9cb998571b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>aa5e61b8-18e5-4367-83ac-3293b79de9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${GlobalVariable.TomorrowDay}</value>
      <webElementGuid>820ae4ad-1970-4e11-974c-80489b739cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d_1_0&quot;)</value>
      <webElementGuid>801e64e5-ee53-4dc5-a052-b188b8f7b890</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='d_1_0']</value>
      <webElementGuid>33ff3d67-96de-485d-89c0-755f23c7fb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/app-dialog-container/app-employee-form-popup/div[2]/form/div/div[3]/div/lib-angular-mydatepicker-calendar/div/div/lib-day-view/table/tbody/tr[2]/td</value>
      <webElementGuid>e1c1843d-22e6-43f2-a051-df2fa8943bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun'])[1]/following::td[8]</value>
      <webElementGuid>d18b26d2-0de0-4eac-8564-2efe31c3e903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat'])[1]/following::td[8]</value>
      <webElementGuid>ebc6becd-1a7f-4b52-9ef2-61a80af31aab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حقل مطلوب'])[2]/preceding::td[35]</value>
      <webElementGuid>49bde277-152e-413a-8af5-e6fa1f32eb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lib-day-view/table/tbody/tr[2]/td</value>
      <webElementGuid>29427f33-fda8-4481-b8a1-4ed25172ddca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'd_1_0' and (text() = '6' or . = '6')]</value>
      <webElementGuid>6602d78d-4ea2-411e-9d16-bd3635c9baef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
