<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__Home</name>
   <tag></tag>
   <elementGuidId>6501a9bd-9534-48a2-889c-158bf4dde4ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdi.custom-icon-size.mdi-home.ng-tns-c55-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-back-logout-items']/button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>bd5eac23-8b33-48e8-8aee-9f099cda091d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi custom-icon-size mdi-home ng-tns-c55-2</value>
      <webElementGuid>6d190ad5-0bb7-449c-81bf-bacad28e73a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-back-logout-items&quot;)/button[@class=&quot;icon-btn ng-tns-c55-2&quot;]/i[@class=&quot;mdi custom-icon-size mdi-home ng-tns-c55-2&quot;]</value>
      <webElementGuid>9be19522-8ac7-4945-a614-4d081b8ed566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-back-logout-items']/button[2]/i</value>
      <webElementGuid>1033b518-91ed-41cd-b42d-72eb31727bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>7a0ab5d8-d574-47b5-b741-809bfceb6611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
