<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Send (Launch)</name>
   <tag></tag>
   <elementGuidId>9b9e17e1-ac96-405a-99aa-7f01a6fb78f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a17bf8ad-aae5-44d0-a0d5-e46338d42a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إرسال</value>
      <webElementGuid>907cc195-64d4-4a49-92e4-6cc6aef696a0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
