<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Old license number field</name>
   <tag></tag>
   <elementGuidId>8c232ed1-dc00-4496-8d86-03fc85c4c46e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oldLicenseFullSerial']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oldLicenseFullSerial</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1a75559-76ac-4404-a6a5-51a0af5ae75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>2f8cd566-da63-4a7b-a911-27a8d897251d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78cff406-6149-4add-a201-3b4203900dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>19ecada7-3196-4403-9234-0a13d74eb8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>310356ee-5ee8-4c56-aabb-804598fae817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>1e00b503-2032-4d0b-b024-c9b8892e0a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldLicenseFullSerial&quot;)</value>
      <webElementGuid>24f5ed9e-2091-4b20-b88a-a7e276ff9c00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oldLicenseFullSerial']</value>
      <webElementGuid>55793ae8-bf82-4492-a28d-7833bfd19f17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div/div[3]/div/input</value>
      <webElementGuid>86e06b3f-7fd6-4e1f-ba38-9e9c052d71d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>fca8ec4b-ff05-4a3c-9bf7-ca3798fc48d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'oldLicenseFullSerial']</value>
      <webElementGuid>d0b49ddb-3480-450e-90e6-4d464e1ca86f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
