<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__licenseDurationType</name>
   <tag></tag>
   <elementGuidId>fab68679-e08a-48e1-9985-fcaf0029b933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='licenseDurationType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-input > #licenseDurationType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c9cc20e-5a26-463a-bb97-bd78e6c9a279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>22a6bab1-b04e-4ebc-bede-112179f8fd77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36fcd24d-7cbe-4892-ba67-1fdcb04edd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aee118a6-fccd-41b5-9ef1-d1d0a750260d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>47566c13-a77b-49e3-bbbf-854695e03335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c8c81fea-eb27-4c8a-82cf-427d6caa85ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licenseDurationType</value>
      <webElementGuid>95e75ce4-8634-4b96-ba01-1806caf9f667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>acf33bdb48b3-0</value>
      <webElementGuid>9021ec7d-8505-49e3-88d0-dd86d164ce7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>acf33bdb48b3</value>
      <webElementGuid>50a1ca6f-9384-441f-8dd4-2d88a359badc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c124-55 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c124-55 ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-md-4 col-sm-12 mb-4 position-relative&quot;]/ng-select[@id=&quot;licenseDurationType&quot;]/div[@class=&quot;ng-select-container ng-has-value&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[@id=&quot;licenseDurationType&quot;]</value>
      <webElementGuid>d2290f8c-745a-4ef1-9ace-bb0c4796a924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='licenseDurationType']</value>
      <webElementGuid>465e5f60-200a-433d-a432-eb5b1d10aa43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='licenseDurationType']/div/div/div[3]/input</value>
      <webElementGuid>470fabd0-7f8a-46f9-bf61-b51fc6a650f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ng-select/div/div/div[3]/input</value>
      <webElementGuid>9db1d8ec-7a22-442d-affa-b80d270089e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'licenseDurationType']</value>
      <webElementGuid>051899df-6a85-4284-a0d9-7109ed83a662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
