<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mark_Fundraising</name>
   <tag></tag>
   <elementGuidId>7d0d7798-2dbf-42d4-86a6-041c013f86e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-item-list']/app-sidebar-menu-item-list/ul/li/app-sidebar-menu-item-list/ul/li/a[2]/span/mark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mark</value>
      <webElementGuid>8b0dda4c-1951-461f-85d1-fd4cd66a7a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>جمع تبرعات</value>
      <webElementGuid>7b85c67c-8331-41e8-92ca-55801c54dc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-list&quot;)/app-sidebar-menu-item-list[@class=&quot;ng-tns-c55-141 ng-tns-c54-142 ng-star-inserted&quot;]/ul[@class=&quot;ng-tns-c54-142 level-1 sidebar-menu-list&quot;]/li[@class=&quot;sidebar-menu-item ng-tns-c54-142 parent-menu-item has-children ng-trigger ng-trigger-expendCollapse ng-star-inserted&quot;]/app-sidebar-menu-item-list[@class=&quot;ng-tns-c54-229 ng-tns-c54-142 ng-star-inserted&quot;]/ul[@class=&quot;ng-tns-c54-229 level-2 sidebar-menu-list&quot;]/li[@class=&quot;sidebar-menu-item ng-tns-c54-229 px-2 ng-trigger ng-trigger-expendCollapse ng-star-inserted&quot;]/a[@class=&quot;d-flex flex-row align-items-center overflow-hidden ng-tns-c54-229 px-2 justify-content-start&quot;]/span[@class=&quot;flex-grow-1 sidebar-menu-item-text text-truncate ng-tns-c54-229&quot;]/mark[1]</value>
      <webElementGuid>df244581-04e2-409c-8f40-f59863665731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-item-list']/app-sidebar-menu-item-list/ul/li/app-sidebar-menu-item-list/ul/li/a[2]/span/mark</value>
      <webElementGuid>0fa34a0f-4d7d-42cb-a210-6c475015b35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='خدمات التحصيل'])[1]/following::mark[1]</value>
      <webElementGuid>29819003-f59f-4165-9cf5-e51c621490e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الخدمات الالكترونية'])[1]/following::mark[1]</value>
      <webElementGuid>5609f5e1-ea3b-4634-b703-d1b507e9cf40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بريد المستخدم'])[1]/preceding::mark[1]</value>
      <webElementGuid>00ef7248-7238-4df9-b521-26ec792a90cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بريد المجموعة'])[1]/preceding::mark[1]</value>
      <webElementGuid>a1f6bfe2-4284-4228-a7bb-20be655abdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mark</value>
      <webElementGuid>d712a2f0-0d89-47bf-861c-3e5f06f19d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mark[(text() = 'جمع تبرعات' or . = 'جمع تبرعات')]</value>
      <webElementGuid>26c19950-309e-4f80-9979-c64eac569569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
