<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__workingMechanism</name>
   <tag></tag>
   <elementGuidId>67feb656-26aa-4a8b-a67c-627a53e1bafc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='workingMechanism']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#workingMechanism</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>35726618-5e24-4f4a-a104-4786f069ceda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>workingMechanism</value>
      <webElementGuid>e30a089f-7462-43d5-9fc8-2d51c41029f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>workingMechanism</value>
      <webElementGuid>cb86d82d-8ca9-4dda-bbb2-c65e252ee3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>workingMechanism</value>
      <webElementGuid>4a6b356e-c98c-484b-ae49-b591ee5f4177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workingMechanism</value>
      <webElementGuid>54860d5d-4177-46b2-bc95-8cc45b70f158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a202fa78-1de9-4573-bccd-54a198396b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>bf859947-8a0d-4005-b287-411b66478540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workingMechanism&quot;)</value>
      <webElementGuid>a4dc0bca-d0c8-4d5d-8265-c101cf6d050d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='workingMechanism']</value>
      <webElementGuid>302b73e6-689a-4460-9b27-4b2cb4181bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[4]/div/textarea</value>
      <webElementGuid>b6b61d05-00ed-45be-9334-0f7ed1bb285c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/textarea</value>
      <webElementGuid>58f91f5a-bb26-4479-8664-70e5f246948d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'workingMechanism' and @id = 'workingMechanism']</value>
      <webElementGuid>371c50c8-acf5-412b-bf13-3cb9057b25a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
