<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__riskAssessment</name>
   <tag></tag>
   <elementGuidId>df78ee7c-3c00-4d61-8bd7-09c6e69ba80b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='riskAssessment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#riskAssessment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b77c17a4-ef33-48e3-a53e-743aebcd1784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>riskAssessment</value>
      <webElementGuid>c5b4714f-7e57-4405-8671-d6c07e064a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>riskAssessment</value>
      <webElementGuid>72da4bfc-f3bd-43d2-94e7-5d87c95d44a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>riskAssessment</value>
      <webElementGuid>1b384f5e-08d7-4e68-8a0e-ff8415961045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>riskAssessment</value>
      <webElementGuid>cc2897a6-f654-432a-b781-9ff1f65963ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f786e2db-1c79-4dc9-b14c-113fc92547c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8e4ec8bd-f1bd-4f7c-83ab-f3e7a37d61a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;riskAssessment&quot;)</value>
      <webElementGuid>2fd69d38-c935-4e23-ab2f-c36171d75687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='riskAssessment']</value>
      <webElementGuid>f4a8a689-e897-46e2-84b6-87806b35e69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[5]/div/textarea</value>
      <webElementGuid>6a239c53-f675-4134-9458-ce1b17ac9f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/textarea</value>
      <webElementGuid>8826e69c-831d-4e1f-824e-81dc6ea559c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'riskAssessment' and @id = 'riskAssessment']</value>
      <webElementGuid>767b2514-dc91-4b99-a9e0-bd5d9bd84310</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
