<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__AccountSearch</name>
   <tag></tag>
   <elementGuidId>d2d1ba8d-8204-46ac-96a9-be9bd35275a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.input-group.ng-touched.ng-dirty.ng-valid > button.input-group-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-list-1-content']/tab/div/div[5]/div/div/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>766b204c-ed72-4c6d-8f46-2ad27ab26d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-text</value>
      <webElementGuid>18b2fa0c-1dcc-4732-a8be-5b47fefc882e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c137-47 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c137-47 ng-star-inserted&quot;]/div[@class=&quot;row mt-3 ng-star-inserted&quot;]/div[@class=&quot;col-12 mb-4 position-relative&quot;]/div[@class=&quot;merge-accounts-container&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-md-4 col-sm-12 mb-4 position-relative&quot;]/div[@class=&quot;input-group ng-touched ng-dirty ng-valid&quot;]/button[@class=&quot;input-group-text&quot;]</value>
      <webElementGuid>f4b81f34-2f9b-400c-9d4b-71d0309ad1ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[5]/div/div/div/div/div/button</value>
      <webElementGuid>b7ca5ae4-3fc1-4aae-9fb9-92ab7d2e7634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم الحساب'])[1]/following::button[1]</value>
      <webElementGuid>abf3743a-6311-411c-a464-e2f6615d93b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الهدف'])[1]/following::button[1]</value>
      <webElementGuid>037518fe-db2f-44f6-86f8-106e2d6006fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الحسابات البنكية المختارة'])[1]/preceding::button[1]</value>
      <webElementGuid>42dcfce5-ca54-432f-b08c-057322542c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم الحساب'])[2]/preceding::button[1]</value>
      <webElementGuid>cb9f5904-82c8-4d6d-aea9-624a21868ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/button</value>
      <webElementGuid>88c74603-bc2c-4895-9fcc-12c658d635e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
