<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bankAccountSearchCriteria</name>
   <tag></tag>
   <elementGuidId>2faf909e-635e-4c25-bc99-3c38356fec30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bankAccountSearchCriteria']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bankAccountSearchCriteria</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>724ae447-02ba-4a05-973e-40b0676e2dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bankAccountSearchCriteria</value>
      <webElementGuid>d78443be-0e37-4826-97a2-80ec3296c60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>bankAccountSearchCriteria</value>
      <webElementGuid>0d179df2-c56a-4328-81d2-b37dadfe8873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>bankAccountSearchCriteria</value>
      <webElementGuid>719aba24-d68f-4cd5-a76a-12a18c53ec2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>67cc70dc-a846-4943-84b1-b892d967b728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankAccountSearchCriteria&quot;)</value>
      <webElementGuid>e640d866-57e4-40bc-9876-22edbca3c1a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bankAccountSearchCriteria']</value>
      <webElementGuid>2e45c36e-c07f-4d84-aefd-b173cbcd007c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[5]/div/div/div/div/div/input</value>
      <webElementGuid>773bc161-405d-4211-a35e-90cd54d62819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/input</value>
      <webElementGuid>75317e9a-426b-48ca-84c4-e322f9f81792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bankAccountSearchCriteria']</value>
      <webElementGuid>ccd96b5c-bae5-44a8-815d-a1cbe0dfaf90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
