<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__swiftCode</name>
   <tag></tag>
   <elementGuidId>1b87fcee-c82b-457b-88b2-9a893ae5a75a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#swiftCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='swiftCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac0baa0c-b163-43b8-9c1b-d95560a6cc60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swiftCode</value>
      <webElementGuid>15b61dae-de4f-4baf-a844-0ef713deb615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>swiftCode</value>
      <webElementGuid>9c7b9ba0-e823-4417-88a0-ed897a7c249a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>swiftCode</value>
      <webElementGuid>c1fe4e26-996f-4bd2-9a21-ee1ee3351dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3e6a2b58-eeaf-4b07-aa84-7d73a88ad67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiftCode&quot;)</value>
      <webElementGuid>5c82aa73-6e9f-4788-8a38-8269d1a24c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='swiftCode']</value>
      <webElementGuid>607ef8eb-5268-4c8c-abde-fa5f1c1c5724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[6]/div[3]/input</value>
      <webElementGuid>120df3ab-8d19-452a-87d1-e0d654900b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/input</value>
      <webElementGuid>c4621482-b071-4cfc-9fac-d5187743d3b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'swiftCode']</value>
      <webElementGuid>8a76be36-ba83-4ecc-8329-d9163fd563c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
