<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__selectedResponsiblePerson</name>
   <tag></tag>
   <elementGuidId>564f6169-adc3-4af1-bcdb-8d725052a96c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectedResponsiblePerson</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectedResponsiblePerson']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13131999-f66f-4745-b106-7ca3af89e0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectedResponsiblePerson</value>
      <webElementGuid>5b461d8f-22fb-42f8-8287-03067f37eac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>selectedResponsiblePerson</value>
      <webElementGuid>51ff7a55-0480-4018-97f9-4cc45ab80ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>selectedResponsiblePerson</value>
      <webElementGuid>31654f23-1f1e-4571-99f8-37e9c9e5821c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-valid ng-touched ng-dirty</value>
      <webElementGuid>fc34fcfc-0222-4c4f-bfa7-3950cd886a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedResponsiblePerson&quot;)</value>
      <webElementGuid>ce799ced-c6d3-4628-b332-21bf671e94b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectedResponsiblePerson']</value>
      <webElementGuid>c64da665-a0f4-4da1-a589-ca936bf51368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[7]/div/div/div/div/div/input</value>
      <webElementGuid>6470d2d9-8885-4798-9e16-d8f8c394e2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/input</value>
      <webElementGuid>7375bbe3-df29-4871-8df5-e4f4e0aa391d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'selectedResponsiblePerson']</value>
      <webElementGuid>c6644ca6-2a01-417f-bd10-83b97f3e3dc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
