<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__oldLicenseFullSerial</name>
   <tag></tag>
   <elementGuidId>bd8090cf-8afd-4f32-b02a-f0741e1b0398</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oldLicenseFullSerial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oldLicenseFullSerial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cedfc8cb-60a2-45a5-b81b-1b943cb1bb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>d1802a62-98b7-4da2-b196-ca49801bb130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>c293079a-4c6e-4e88-8f3c-4ea7bd197f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>332b7c67-dedd-445e-9a33-52ad41c96804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>bd58f165-5488-40c2-8e65-45b73c0888f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldLicenseFullSerial&quot;)</value>
      <webElementGuid>2c227d23-b029-4411-b41d-942f1504e489</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oldLicenseFullSerial']</value>
      <webElementGuid>163e3833-2eca-4219-b484-74d1137ce59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/div/div/input</value>
      <webElementGuid>cfdfd16a-ebea-4daf-92ea-decbe83b025f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d0b7c2c5-5d82-4094-89f1-e17d30eebf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'oldLicenseFullSerial']</value>
      <webElementGuid>55bf8513-1b91-4046-8387-73aaebef4af0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
