<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__accountNumber</name>
   <tag></tag>
   <elementGuidId>c7bfc766-2e90-4222-bfe6-949879f5d5d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accountNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accountNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>094fea0b-f225-4e4a-ab95-9266e49cc09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountNumber</value>
      <webElementGuid>7ea757b8-34c1-411d-9ae6-35f96c717a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>accountNumber</value>
      <webElementGuid>9e7113e9-b77f-4c96-964b-dd79dd61cf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>accountNumber</value>
      <webElementGuid>9758a0cb-10ed-4f3f-a13c-54f17bf40fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>009b74e9-ba27-4030-889c-1b0d43decb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountNumber&quot;)</value>
      <webElementGuid>cc17d15d-2971-4874-aa96-8641b8ecc3ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accountNumber']</value>
      <webElementGuid>b6417b34-ac18-4cff-bdb3-44ee07b78e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[6]/div/input</value>
      <webElementGuid>24134aa3-0770-4503-b464-6ddd093b1a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>a996b219-6d49-4826-93e0-8630fc16a688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accountNumber']</value>
      <webElementGuid>cded7777-e4fa-4975-ad1b-5fb48fb43fd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
