<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__iBan</name>
   <tag></tag>
   <elementGuidId>b5c57512-5910-4657-a8ec-e9894aafa58d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iBan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='iBan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f417bc86-141e-4178-84c9-57ba6d354ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iBan</value>
      <webElementGuid>91741543-491e-41ea-8cd8-3f9e9e224ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>iBan</value>
      <webElementGuid>fc8348af-19ee-478f-9075-e018fe3243e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>iBan</value>
      <webElementGuid>317d0009-65d7-47b6-8ee8-250b75809769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>59dc849e-9d60-46cf-8f12-3f76a17c62d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iBan&quot;)</value>
      <webElementGuid>a1a57f77-8b59-481d-a977-ec73353e0906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iBan']</value>
      <webElementGuid>7fcfbc75-60e4-4e0e-9a94-b5e45af7e326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[6]/div[2]/input</value>
      <webElementGuid>6f6c7f6f-75a8-48fc-a69e-173b7a47a1d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>b0b60541-1e8e-494e-aa40-a04d8f2f8001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'iBan']</value>
      <webElementGuid>89876bac-6d60-4119-862d-54c282797e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
