<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__purpose</name>
   <tag></tag>
   <elementGuidId>98c5ddad-e349-4902-8d9d-58577c712548</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#purpose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='purpose']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1d9f4ba7-f7ba-4100-9beb-3e3e2dd6415f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a99a8fba-4f78-4c51-9818-53b0e9f6c622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>purpose</value>
      <webElementGuid>cd966741-24cd-4dae-9d91-cbcd4569ece2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>purpose</value>
      <webElementGuid>fe02d90c-0c0a-46fe-98ba-1254b9aa0390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>purpose</value>
      <webElementGuid>6149a471-bc96-460b-a1ce-bccb15fcb45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched is-invalid</value>
      <webElementGuid>855c04f5-9046-4223-9852-da0e6d85de06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;purpose&quot;)</value>
      <webElementGuid>ca5614cc-7b42-4603-ae8c-f692d46fb911</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='purpose']</value>
      <webElementGuid>32de4554-43a5-48d9-9da5-d61a3d303e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[4]/div/textarea</value>
      <webElementGuid>ad1aa1fa-0ca4-4aa8-b6db-c752d7f00d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::textarea[1]</value>
      <webElementGuid>ba07fa40-d74d-47f4-ae64-109a6378c379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حقل مطلوب'])[2]/preceding::textarea[1]</value>
      <webElementGuid>2131bb54-3dd2-40e9-a933-5aa7ea2c2a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>dac9caf2-10ec-48bc-af81-6d9286ce1f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'purpose']</value>
      <webElementGuid>60b7e9eb-df63-489a-b114-7346675b9f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
