<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_close (collector upload screen)</name>
   <tag></tag>
   <elementGuidId>898b5554-3af0-4781-91c9-c82110b8b47b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='من'])[2]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dialog-actions > button.btn.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c55c49c5-242b-4ee2-8c81-cdf70b199999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>ca299e29-ae7d-4ef0-a17b-d018404dfadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>أغلق</value>
      <webElementGuid>dc56daba-2e60-4150-83ac-304d2789c63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-5&quot;)/app-dialog-container[@class=&quot;ng-tns-c40-187 ng-trigger ng-trigger-dialogContainer ng-star-inserted rounded shadow&quot;]/custom-attachment-popup[@class=&quot;dialog-item ng-star-inserted&quot;]/div[@class=&quot;dialog-actions&quot;]/button[@class=&quot;btn btn-secondary&quot;]</value>
      <webElementGuid>a1401f9a-4d7d-426a-b8d8-6be22eaeb056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-5']/app-dialog-container/custom-attachment-popup/div[3]/button</value>
      <webElementGuid>c0cdf0a3-99ab-4fc1-9fb9-3d8acd21b5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='من'])[2]/following::button[1]</value>
      <webElementGuid>88e987cc-c9db-4707-a2a0-ad142d69fb5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::button[1]</value>
      <webElementGuid>577a8c0e-9c88-4355-bbb3-2a1d468dc578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='أغلق']/parent::*</value>
      <webElementGuid>64138c8a-9117-4cb3-83b0-9f3b91ab9c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>5430415b-d1bd-484f-9b9b-7aedc57c52c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'أغلق' or . = 'أغلق')]</value>
      <webElementGuid>fc64edd7-e07e-463a-829a-f35982bfdadf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
