<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Launch (send request)</name>
   <tag></tag>
   <elementGuidId>54cf8485-fc15-43ca-9c4e-2b04137d853c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e-service-wrapper']/div[2]/div/div/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cd67a38-3e4c-4b65-a22d-71f3fbc1cce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary ng-star-inserted</value>
      <webElementGuid>132d8f5f-e07a-49ff-929e-fc8bf791bbc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>إرسال</value>
      <webElementGuid>3d1738b7-4d74-43f5-865f-ee216e40bef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e-service-wrapper&quot;)/div[@class=&quot;row mt-4 mb-2&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;d-flex flex-row flex-wrap gap-2 justify-content-center&quot;]/button[@class=&quot;btn btn-primary ng-star-inserted&quot;]</value>
      <webElementGuid>3deb0538-189d-435e-a405-305d3c3e3a93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e-service-wrapper']/div[2]/div/div/button[2]</value>
      <webElementGuid>8ee13065-c25b-40af-bbd7-f556c99bba4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='حفظ'])[1]/following::button[1]</value>
      <webElementGuid>504d4d94-18ed-471a-b692-665fe0bdfa02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='من'])[1]/following::button[2]</value>
      <webElementGuid>64c0158a-60d2-429c-8a0f-7358204b7dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جميع حقوق النشر محفوظة © هيئة تنظيم االأعمال الخيرية'])[1]/preceding::button[2]</value>
      <webElementGuid>1f09085b-6496-4004-938a-402627557c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button[2]</value>
      <webElementGuid>19f7c0fb-717e-41af-bd69-4f0ba52ed043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'إرسال' or . = 'إرسال')]</value>
      <webElementGuid>86a9f424-54d8-4eee-8bd5-8e5dd1f59e7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
