<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NA_attachmentUploader</name>
   <tag></tag>
   <elementGuidId>ccd0d1c6-eb01-4cb8-83e2-0fcf84bc58a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attachmentUploader</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attachmentUploader']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec54912e-77ad-4344-a7c6-80672a5f3d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>7a2625b5-4c81-4db9-a738-242183c04a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attachmentUploader</value>
      <webElementGuid>e0bb1995-26c2-46f2-83e9-56f8dccf100b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf</value>
      <webElementGuid>eb07d477-6e42-49ad-869d-b7b07cb737eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attachmentUploader&quot;)</value>
      <webElementGuid>616b0caa-9553-4a20-ae9f-4d37c8b99da1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attachmentUploader']</value>
      <webElementGuid>1f056c3c-7d3b-41e8-ab43-e7eb5be54464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/attachments/div/input</value>
      <webElementGuid>69ebba0b-2c29-4d3e-bfc0-fa30e0c7a793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//attachments/div/input</value>
      <webElementGuid>8845c673-1e29-4de2-8c93-224545c7fc83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'attachmentUploader']</value>
      <webElementGuid>365cf376-b20b-447a-92bb-15794ebac030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
