<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__collectorNumber</name>
   <tag></tag>
   <elementGuidId>9315e4f9-2c3f-4781-b579-694f9e1cd7c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collectorNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='collectorNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1b02ea8-3c33-4c91-a745-0c8bf160b44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collectorNumber</value>
      <webElementGuid>d81680be-15fb-43ad-b623-59274cc422ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>collectorNumber</value>
      <webElementGuid>2353cc2e-ff79-44a2-9898-9964070c9f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>collectorNumber</value>
      <webElementGuid>3f57b84a-2da6-4865-9f4c-d664f1425ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ef9e4d8d-178a-4701-b0fc-9f18051e7398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collectorNumber&quot;)</value>
      <webElementGuid>aa47eea2-032f-4683-ae09-b78fc0197c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='collectorNumber']</value>
      <webElementGuid>140dbfda-53d6-461d-ae89-0facf7ad62df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collector-item/form/fieldset/div[2]/div[2]/input</value>
      <webElementGuid>e38adc92-44c4-4cf1-bc40-90a8d0159ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div[2]/input</value>
      <webElementGuid>f7eb086c-777d-457a-ad47-4c6db612379b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'collectorNumber']</value>
      <webElementGuid>241e5f9d-a9d7-4cac-a91c-f3c717db8835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
