<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__oldLicenseFullSerial</name>
   <tag></tag>
   <elementGuidId>6edc42be-6ff5-4ef9-a80a-7feae6b51f64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oldLicenseFullSerial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oldLicenseFullSerial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f13a3ec5-9030-4db3-b0f3-9e981e5c9323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>79768d43-58b3-4bd2-bbfe-020bba90f206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>721b60d6-c2d3-4d48-9dac-70f58e9f05ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-valid ng-touched ng-dirty</value>
      <webElementGuid>af7a4e65-1863-42a8-a565-15033bbf0323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldLicenseFullSerial&quot;)</value>
      <webElementGuid>2a5a5ab0-ac3d-4f2d-9d53-7e8f0f437194</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oldLicenseFullSerial']</value>
      <webElementGuid>06d8a3ec-f47b-4395-b54f-efd2a946cae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collector-item/form/fieldset/div/div/div/input</value>
      <webElementGuid>5734c09e-4311-45ad-b5f3-85fbeb14ac84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/input</value>
      <webElementGuid>1249d4c1-9fa4-4ee6-bd1d-1169be1e86c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'oldLicenseFullSerial']</value>
      <webElementGuid>19cc606e-1b9e-4f41-a942-154d91ec06e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
