<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__arabicName</name>
   <tag></tag>
   <elementGuidId>738cba2a-86ca-471f-bff8-5615edef6038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arabicName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='arabicName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cbcf69a-94cb-4261-8928-58fee06a8870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arabicName</value>
      <webElementGuid>52560a9d-ae97-42b8-b6f3-9a4d19c995ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>arabicName</value>
      <webElementGuid>aefab282-96c6-4805-a04a-14bb3597ba89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>arabicName</value>
      <webElementGuid>a36ebdfa-9c5d-453a-a722-51a04bd00df0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6d60d36f-66ae-4f45-8344-45f3bdaf8de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arabicName&quot;)</value>
      <webElementGuid>ad58994b-36c5-4d5a-8a7b-32c73ccaaeb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='arabicName']</value>
      <webElementGuid>de83de02-ed25-4796-bc81-81425df33500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collector-item/form/fieldset/div[2]/div/input</value>
      <webElementGuid>e437809b-4a55-4fb6-a992-ba3adc9a0397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/input</value>
      <webElementGuid>06baec44-f105-47f9-b1e8-28b2d0ea4b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'arabicName']</value>
      <webElementGuid>90d82ba8-04a9-468b-ac1c-79aac907dcf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
