<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__identificationNumber</name>
   <tag></tag>
   <elementGuidId>4f7a90d7-9f2b-4bc3-ae63-5f83f21d2498</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identificationNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identificationNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4e98812-8f31-458d-a0cd-0cf06fff2522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>8fa086da-067d-49cb-9160-b01be9ea3765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>24ac8553-e0cd-4b29-8933-7fad1ebfee14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>b19123e6-a377-4e19-bf2e-276c7d123cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c59835ea-f4df-4127-b09c-bd7083e89ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identificationNumber&quot;)</value>
      <webElementGuid>7ec05db4-1f56-428e-9885-b2ac30d7b9f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identificationNumber']</value>
      <webElementGuid>8232e1d0-6868-4e2b-af37-d1b5ebd58f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collector-item/form/fieldset/div/div[2]/input</value>
      <webElementGuid>f6592a36-f7c5-46e8-9762-9ace5c24ba92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/input</value>
      <webElementGuid>f9b75ed7-b8f4-42d1-8607-1b46cd14284b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'identificationNumber']</value>
      <webElementGuid>12296a70-5ee5-4989-ac1d-4a7b49e743f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
