<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__licenseStartDate (1)</name>
   <tag></tag>
   <elementGuidId>3b7a9335-28a3-4ef9-9f2e-5b8388e90b4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='licenseStartDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#licenseStartDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4183aa1f-fa94-4e0b-a593-a2b3e87c3502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>licenseStartDate</value>
      <webElementGuid>36871dd7-5837-4664-9cd4-23561080d7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licenseStartDate</value>
      <webElementGuid>23fc2396-a083-46dd-b37b-331a65676efd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>licenseStartDate</value>
      <webElementGuid>f89f7b1c-3d5d-477c-990a-170c5cf10a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>554d3102-a498-4fc4-95d1-cb14ef431dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licenseStartDate&quot;)</value>
      <webElementGuid>15b89dda-30ec-4760-94ea-65656deb0e56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='licenseStartDate']</value>
      <webElementGuid>c44026d0-bf55-49a7-b988-40c8dddaf31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-70']/app-dialog-container/action-with-comment-popup/div[2]/div/form/div/div/div/div</value>
      <webElementGuid>85e25763-069a-46ba-a15c-97f508ee5c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div</value>
      <webElementGuid>42bdd3c7-6c13-4274-a06f-2d249166c83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'licenseStartDate']</value>
      <webElementGuid>4a08060d-1eda-4454-8648-917e7b0fcc99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
