<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__licenseEndDate</name>
   <tag></tag>
   <elementGuidId>b19829b0-2352-4e46-a687-9b6fdd0de36d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#licenseEndDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='licenseEndDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e911481c-718f-459f-9695-fa46f924fbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licenseEndDate</value>
      <webElementGuid>65afabee-de4d-4234-bf6c-7ce6b02b439a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d2e5284a-e0a2-4385-87b4-612f398f4d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licenseEndDate&quot;)</value>
      <webElementGuid>6aae8859-d972-4f9a-bef8-c6b26bf7d458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='licenseEndDate']</value>
      <webElementGuid>f0662ae6-2dd1-47ec-8d1e-454f0b058a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/transfer-funds-abroad-approve-task-popup/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>ceeb3a08-82e6-4c6a-914c-76e802c4a734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div</value>
      <webElementGuid>59c11190-65a2-42d0-9f93-935aa306ee8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'licenseEndDate']</value>
      <webElementGuid>450705ee-9c11-46e3-a85c-42c4962d86eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
