<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__followUpDate (1)</name>
   <tag></tag>
   <elementGuidId>68ca0179-dcaa-440b-be1a-5d8162f2a4ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='followUpDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#followUpDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d9f0c63-fd50-464d-bc9f-076c14482e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>followUpDate</value>
      <webElementGuid>11da3a5b-79c0-4fde-99ee-e8f0645dace9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>followUpDate</value>
      <webElementGuid>939c9d82-376f-4c00-a35c-f736dcdada37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>followUpDate</value>
      <webElementGuid>59e0aa47-4d9d-4218-9b89-e7536febdbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c4be0c65-1566-4c38-ae3c-433728397c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;followUpDate&quot;)</value>
      <webElementGuid>b8b3d312-b552-4577-b3aa-2cf2ba5164a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='followUpDate']</value>
      <webElementGuid>5694289f-32e3-4124-aa53-d1eb84a77653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-70']/app-dialog-container/action-with-comment-popup/div[2]/div/form/div[2]/div/div/div</value>
      <webElementGuid>78506fd4-2fea-4001-8370-de723d4f1699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>91d7d5ed-b83c-40ef-87aa-fcb249ff0a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'followUpDate']</value>
      <webElementGuid>3d1fb1c8-49c8-4fed-bea7-0881cbbbb2f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
