<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__licenseStartDate</name>
   <tag></tag>
   <elementGuidId>4b4ab0e2-8cd6-4f8e-96e6-a098dbb99318</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#licenseStartDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='licenseStartDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd67ca36-5601-42da-97b8-3b3fb054cdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>licenseStartDate</value>
      <webElementGuid>835e2c40-b8f2-4c98-b616-9f50d9c244f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licenseStartDate</value>
      <webElementGuid>e136fe6a-6a13-4fa2-a99a-05d08363ec70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>licenseStartDate</value>
      <webElementGuid>27bec82e-3736-4e48-af51-a640fb6ff456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7918c1a6-9ae6-4141-b592-5b016b3dc668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licenseStartDate&quot;)</value>
      <webElementGuid>c21e08f0-ee12-4459-b4fe-6248e75a165a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='licenseStartDate']</value>
      <webElementGuid>292f2502-f32f-410f-9411-972259ebae61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/employment-approve/div[2]/form/div/div/div</value>
      <webElementGuid>134490db-95d5-4643-b3c5-539cbca7d89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div</value>
      <webElementGuid>af71736f-772c-4c75-ac74-77db1c6fb6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'licenseStartDate']</value>
      <webElementGuid>c8f8a799-7013-4e60-a6b3-ee9d533b1177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
