<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__licenseDuration (1)</name>
   <tag></tag>
   <elementGuidId>eefd0fa3-0a8b-4549-9200-6e15873016ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='licenseDuration'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-12.col-md-6.mb-3.position-relative.ng-star-inserted > #licenseDuration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b48cd895-5b55-49e8-8ccd-0e3b76b7a194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licenseDuration</value>
      <webElementGuid>5fdec88c-5924-46cc-9599-e8035066aa6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>licenseDuration</value>
      <webElementGuid>03c69873-9d10-4615-b259-1f082bbf3bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>licenseDuration</value>
      <webElementGuid>251cd4c5-52db-4457-a25e-9199af94615f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-valid ng-touched</value>
      <webElementGuid>cde6a958-f38e-4666-9dea-10571f7f06b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-5&quot;)/app-dialog-container[@class=&quot;ng-tns-c3-122 ng-trigger ng-trigger-dialogContainer ng-star-inserted rounded shadow&quot;]/action-with-comment-popup[@class=&quot;dialog-item ng-star-inserted&quot;]/div[@class=&quot;dialog-content no-fixed-height&quot;]/div[@class=&quot;ng-star-inserted&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-6 mb-3 position-relative ng-star-inserted&quot;]/input[@id=&quot;licenseDuration&quot;]</value>
      <webElementGuid>bb5b007b-ffc2-4586-aba7-4f652e37e42e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='licenseDuration'])[2]</value>
      <webElementGuid>967f38d8-3978-46e6-980e-52502554ad21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-5']/app-dialog-container/action-with-comment-popup/div[2]/div/form/div/div[2]/input</value>
      <webElementGuid>8e7f7eb7-7186-42ef-9864-7a5513b2ff25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/input</value>
      <webElementGuid>78150732-9abc-48dc-94e4-d7c29fd908b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'licenseDuration']</value>
      <webElementGuid>ea680da1-4a5b-4eee-b11d-fa770a18240a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
