<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__licenseDuration</name>
   <tag></tag>
   <elementGuidId>d9a601ae-5811-489a-a002-c620e8de485f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='licenseDuration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#licenseDuration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>045dd4b1-bb8d-4c12-8182-d59f0686e7c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licenseDuration</value>
      <webElementGuid>7b755439-1344-4cca-be5f-d5baf6e04b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>licenseDuration</value>
      <webElementGuid>061f21d3-b338-4bb9-b3aa-ac1fba0af2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>licenseDuration</value>
      <webElementGuid>03d28f10-25c7-40ae-adec-f46c30dbd96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>21c5e9ce-1e41-41a7-8a5d-eb3f58c65d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licenseDuration&quot;)</value>
      <webElementGuid>798aa0aa-6e42-4df2-8f26-5b3141ad6ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='licenseDuration']</value>
      <webElementGuid>9d9a425c-3e02-42e9-870c-5b6428d61693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-70']/app-dialog-container/action-with-comment-popup/div[2]/div/form/div/div[2]/input</value>
      <webElementGuid>132996db-da24-4fbe-a790-1944cc1f22f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/input</value>
      <webElementGuid>8f310eb7-2abe-4219-9cf7-ee60ef6fb5ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'licenseDuration']</value>
      <webElementGuid>1eaa3b4e-0ee4-4fd8-bf96-e84c295ccc6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
