<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__customTerms</name>
   <tag></tag>
   <elementGuidId>7f1c5fba-3736-4770-868e-48ad5b6fc4aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customTerms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='customTerms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ff322d91-0646-4eae-a7ea-e4c41a266131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customTerms</value>
      <webElementGuid>ec623ef9-459b-4ffb-98d6-1995ea8b5855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>customTerms</value>
      <webElementGuid>1ae76827-89ce-499d-9510-33832724b2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>customTerms</value>
      <webElementGuid>e8ffd8c9-7cb7-421e-9e05-3073fc5a1aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5f64d95b-81e0-4902-95d1-cd787b16b79c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customTerms&quot;)</value>
      <webElementGuid>c070b721-fde6-4822-a27e-8b6100495a09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='customTerms']</value>
      <webElementGuid>4aeb7034-a873-4954-8d16-fe00709adb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-3']/app-dialog-container/transfer-funds-abroad-approve-task-popup/div[2]/div[4]/div/textarea</value>
      <webElementGuid>d9c86af5-2915-41ee-87b9-c137003501ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/textarea</value>
      <webElementGuid>c44c1704-8715-4e4c-a3d4-aba9b4aecb86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'customTerms']</value>
      <webElementGuid>6f00a08a-5172-41be-8360-5269f755dcfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
