<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__customTerms (1)</name>
   <tag></tag>
   <elementGuidId>bc01dd0b-9e63-4a7b-ad5b-ca925e9e5be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='customTerms']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customTerms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9fd6a6a8-c225-4404-ab9c-58857139818b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customTerms</value>
      <webElementGuid>4bee37f4-c0c1-42ea-8f01-ea96fc252e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>customTerms</value>
      <webElementGuid>d8aee23c-d265-4108-b4bb-1d9eda33ec23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>customTerms</value>
      <webElementGuid>066e9dd5-bf8e-411d-ad4a-ba668cff7e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>04351ec0-7b45-45ec-97de-0b7404bc2295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customTerms&quot;)</value>
      <webElementGuid>b92ff30b-5c2c-4007-a885-ec3ea9224a95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='customTerms']</value>
      <webElementGuid>d5e326cc-5e7f-4a31-a717-8b80c4d5dcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-70']/app-dialog-container/action-with-comment-popup/div[2]/div/form/div[5]/div/textarea</value>
      <webElementGuid>5a387fd8-8950-48b7-98f3-00a4192a2101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/textarea</value>
      <webElementGuid>270c8976-269d-43c1-8179-9c26180314e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'customTerms']</value>
      <webElementGuid>f809f842-0754-4841-9e42-aa9b1520c91d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
