<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Claim Symbol (Right click)</name>
   <tag></tag>
   <elementGuidId>80d03b7f-7020-46ad-b4d7-717ed18f771d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-hand-back-right.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[4]/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>3b1006be-2d54-4ea4-bf10-f41b75d88fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-hand-back-right ng-star-inserted</value>
      <webElementGuid>0643ad4d-a6ce-48da-a32c-e94c6592ed12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-12&quot;)/div[@class=&quot;position-fixed ng-star-inserted&quot;]/ul[@class=&quot;dropdown-menu show shadow-sm context-menu-item-list scale-0 transition top-left&quot;]/li[@class=&quot;ng-star-inserted&quot;]/button[@class=&quot;dropdown-item context-menu-item d-flex align-items-center justify-content-start px-2&quot;]/i[@class=&quot;mdi mdi-hand-back-right ng-star-inserted&quot;]</value>
      <webElementGuid>ac5ac860-c5f4-4672-a77f-0220111fbb73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-12']/div/ul/li[4]/button/i</value>
      <webElementGuid>caf9a677-b1f1-4542-8287-f8c7b2f2781e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/button/i</value>
      <webElementGuid>8ad33078-0376-4f52-8db2-0f0b3aa3fd2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
