<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__Step checklist</name>
   <tag></tag>
   <elementGuidId>a4a4be31-485b-4b05-bc92-bb242ca8c151</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='check-list-wrapper']/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.text-primary.mdi-format-list-checks</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>493debf1-f48c-4579-92bd-b5a2818ac7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi text-primary mdi-format-list-checks</value>
      <webElementGuid>5311b650-c30d-4e69-b19e-fc3ef9921fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;check-list-wrapper&quot;)/button[@class=&quot;btn icon-btn position-absolute end-100 top-0 m-0 p-2 shadow shadow-sm rounded-1 bg-white border border-1&quot;]/i[@class=&quot;mdi text-primary mdi-format-list-checks&quot;]</value>
      <webElementGuid>fc513671-7207-4a21-b35a-58eaf95e2a95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='check-list-wrapper']/button/i</value>
      <webElementGuid>4eb43592-32aa-4027-93bf-e657e571f187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//step-check-list/div/button/i</value>
      <webElementGuid>637418e1-1ffd-4963-b3a4-0821855ca816</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
