<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>d04f00ca-d917-46e8-b61c-1a01f6bdfbb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.mb-4.btn-primary.shadow.shadow-sm.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0752cc9b-bb52-4f44-8021-bb5a0852bfee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4c3e443c-f789-423c-a306-6cf0e0d7b852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn mb-4 btn-primary shadow shadow-sm ng-star-inserted</value>
      <webElementGuid>a9058011-0c0c-4ff6-a5de-54696831c65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>البحث</value>
      <webElementGuid>cacccb27-c6ae-4c78-9c1a-98336da07516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c124-41 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c124-41 ng-star-inserted&quot;]/button[@class=&quot;btn mb-4 btn-primary shadow shadow-sm ng-star-inserted&quot;]</value>
      <webElementGuid>8d97085d-a113-446a-b64b-839b5f932be1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>70330bb0-941f-42fa-8e49-6b5bf31c0a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/button</value>
      <webElementGuid>2b7cfb3e-5bcc-41c8-be96-f781ad4a9dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='رقم الرخصة'])[1]/following::button[1]</value>
      <webElementGuid>fcb1f3e7-9d8e-49c1-85d8-b78acd8b7365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الموضوع'])[1]/following::button[1]</value>
      <webElementGuid>11bbb060-9988-407e-9bc4-c62874ad7c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='إعادة تعيين'])[1]/preceding::button[1]</value>
      <webElementGuid>bce84309-0f0a-40cc-bebd-f35e039fb91f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جمع تبرعات'])[2]/preceding::button[2]</value>
      <webElementGuid>b97cfb1f-b620-4a97-a2a8-1b9ed1596af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='البحث']/parent::*</value>
      <webElementGuid>1abaebb3-b5bc-4779-b11f-3ed29555d862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab/div/button</value>
      <webElementGuid>0ee646e4-5651-43ae-bc2f-ac5ef9aa558e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'البحث' or . = 'البحث')]</value>
      <webElementGuid>d77f3b83-95a5-44c9-9edb-a7d36fd868eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
