<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Serial number</name>
   <tag></tag>
   <elementGuidId>b5712e84-30e0-4558-ae81-abc5bf6e2235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formly_19_input_fullSerial_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-list-1-content']/tab/div/form/formly-form/formly-field[2]/formly-group/formly-field/formly-field-wrapper/div/div/formly-field-input/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70987f47-ec76-4e75-9735-9e88a239f12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>762b0d4a-a0b9-4b43-951e-ec3a6179a1b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9b1152a-aaeb-4430-af63-8b705c7d9934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formly_19_input_fullSerial_0</value>
      <webElementGuid>1b2ce62e-9877-4368-afc2-0d3d73f34d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d9861c67-baa1-499a-aed2-2f817c82768a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formly_19_input_fullSerial_0&quot;)</value>
      <webElementGuid>483a5ebb-59ac-44c6-9097-65ca78fd9fd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='formly_19_input_fullSerial_0']</value>
      <webElementGuid>dfff7240-54bb-4003-82f4-0b4c7ca6ef81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/form/formly-form/formly-field[2]/formly-group/formly-field/formly-field-wrapper/div/div/formly-field-input/input</value>
      <webElementGuid>5d1a4643-4825-4cf8-8f60-a5bd6ed8054b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الرقم التسلسي'])[1]/following::input[1]</value>
      <webElementGuid>fc9be927-5286-4c75-88e9-524575d5f68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تاريخ الاضافة إلى'])[1]/following::input[1]</value>
      <webElementGuid>c701014d-6dfe-4778-90e1-d602a3f313d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الحالة'])[1]/preceding::input[1]</value>
      <webElementGuid>1011f68c-8208-4b9f-96e0-c4ffebf92c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أختر'])[1]/preceding::input[1]</value>
      <webElementGuid>e6e90c68-6feb-40de-a392-30837b3ba08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//formly-field-input/input</value>
      <webElementGuid>ecf2c40b-092e-43ad-8db6-aa151d6aa1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'formly_19_input_fullSerial_0']</value>
      <webElementGuid>9dd57951-255e-4f30-a378-df05f6929d7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
