<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Transfer purpose TAB</name>
   <tag></tag>
   <elementGuidId>fb3230e2-bbb7-4611-8d94-29371abbfdde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.position-relative.tab-link.active</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@role = 'tab' and (text() = 'الغرض من التحويل ' or . = 'الغرض من التحويل ')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='tab-list-1']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>78cc0904-4069-481b-8e7d-8f2486b333f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>adbc7aa5-0f36-4a7b-8e0c-9ca57f344e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>bf2e4eb0-0b9e-48b7-b555-ef595c37bbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6a06f9ea-cfb9-4f60-862b-ee12d59ea84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link position-relative tab-link active</value>
      <webElementGuid>0695a74b-5c4b-45bb-a551-2f2ddd6b9a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bdefc379-27ac-4779-b7e9-afbab7185e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الغرض من التحويل </value>
      <webElementGuid>0f0e165c-baa1-487a-a34a-b18ba4df2687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1&quot;)/li[@class=&quot;nav-item ng-star-inserted&quot;]/a[@class=&quot;nav-link position-relative tab-link active&quot;]</value>
      <webElementGuid>c8bc0d44-6cdf-43d5-8a80-7b57a3b99261</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tab-list-1']/li[3]/a</value>
      <webElementGuid>e313d43b-d89d-4ad4-b626-ef53668e257c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'الغرض من التحويل')]</value>
      <webElementGuid>c118c651-1304-46b9-8df5-48cd5125dc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بيانات مقدم الطلب'])[1]/following::a[1]</value>
      <webElementGuid>2974fd0b-8ae1-48e8-991f-ece2b94b9f16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='معلومات اساسية'])[1]/following::a[2]</value>
      <webElementGuid>3823a16c-dd6c-4449-9192-ccaece6e12ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='البيانات المالية للطب'])[1]/preceding::a[1]</value>
      <webElementGuid>f8a62e71-96a6-474b-88ee-457e95109ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الشروحات الخاصة'])[1]/preceding::a[2]</value>
      <webElementGuid>1cc8c431-6d88-4dd1-8f08-96a25564f115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الغرض من التحويل']/parent::*</value>
      <webElementGuid>5935be9b-5f6b-4eaf-8c31-2215dc80176a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tabs-list/ul/li[3]/a</value>
      <webElementGuid>6acf7294-9735-4861-837e-0f73e5c2e34a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'الغرض من التحويل ' or . = 'الغرض من التحويل ')]</value>
      <webElementGuid>f8703bae-dafe-4299-86ed-0d797d2314e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
