<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__add purpose icon (pluss icon)</name>
   <tag></tag>
   <elementGuidId>417597e6-2266-4dbd-b1f4-1d0738d6b9be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-plus-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-list-1-content']/tab[3]/div/div/div/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>542f6169-c895-4319-b515-a09f93c2bdb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-plus-box</value>
      <webElementGuid>94bf4ca6-9f75-4efa-9d91-86823018fe8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c130-73 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c130-73 ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col&quot;]/button[@class=&quot;btn btn-link outline-none&quot;]/i[@class=&quot;mdi mdi-plus-box&quot;]</value>
      <webElementGuid>d15f073a-4ecd-424d-b9f7-3ad3fcc1a762</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/div/div/button/i</value>
      <webElementGuid>08d2b105-cb8e-4d28-b0d8-2dc47a4a6916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/div/div/button/i</value>
      <webElementGuid>595620e1-5da6-48e1-903d-3b084a1ff745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
