<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__receiverPassportNumber</name>
   <tag></tag>
   <elementGuidId>b9a1167d-92b0-49f5-8f07-a582cabad531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receiverPassportNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='receiverPassportNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ebce979-3b33-49a3-ada1-763364002219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>receiverPassportNumber</value>
      <webElementGuid>13611950-753c-40cd-afb9-7cfbd12bb596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receiverPassportNumber</value>
      <webElementGuid>56df9c5a-50d6-4396-9f71-6e74eafa523f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>receiverPassportNumber</value>
      <webElementGuid>8b0d9a22-3095-4b86-9a04-dabd6c3f6a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>4782f2b2-92a1-4e46-b00b-7919e02fbcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receiverPassportNumber&quot;)</value>
      <webElementGuid>d78f2fda-8a74-4518-a8ba-273e653aa5fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='receiverPassportNumber']</value>
      <webElementGuid>553da300-1376-4bf4-add2-8a4f8c477918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/div[2]/div[3]/input</value>
      <webElementGuid>2fd4a0dc-5efb-4433-afaf-0d4535396a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/div[2]/div[3]/input</value>
      <webElementGuid>3e2c5ea3-e785-49ed-93f3-0ece0a4ad95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'receiverPassportNumber']</value>
      <webElementGuid>2432c100-5ebb-498d-8e91-a0f148e89948</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
