<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__receiverPhone1</name>
   <tag></tag>
   <elementGuidId>b057aa44-f4a1-4cd0-a0dd-79e492cff859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receiverPhone1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='receiverPhone1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c57d2e92-d620-443e-a243-71b711b0cb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>receiverPhone1</value>
      <webElementGuid>47c31666-0ae9-4cce-9fc8-df95fa16f479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receiverPhone1</value>
      <webElementGuid>c8a40afb-bb09-42a9-9e50-331abaf8f93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>receiverPhone1</value>
      <webElementGuid>f0de3d25-7830-4342-a60a-3b847ed7a99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7617e42c-24be-435e-b45b-9d5afbc1c2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receiverPhone1&quot;)</value>
      <webElementGuid>924b199c-3997-4904-a463-f316bf15523c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='receiverPhone1']</value>
      <webElementGuid>3741865c-3c2a-4cb9-bc6a-dbee40df1bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/div[3]/div/input</value>
      <webElementGuid>3d577957-2af2-4f53-979d-abd43bb2b762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/div[3]/div/input</value>
      <webElementGuid>de6ac326-e7f8-4c3a-b6dd-a6764b06fb83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'receiverPhone1']</value>
      <webElementGuid>8d6e15bd-2831-4b21-b051-053869687728</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
