<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__transferFromIBAN</name>
   <tag></tag>
   <elementGuidId>6d1e5290-dedc-44b5-9448-11b887bbb6d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transferFromIBAN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transferFromIBAN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d94619c-093e-48b5-9e5d-9e77406765fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>transferFromIBAN</value>
      <webElementGuid>f4645070-62bb-4c68-91f9-f497bd1ccb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transferFromIBAN</value>
      <webElementGuid>ba261e4d-ab85-45ae-bbed-ac51548f60ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>transferFromIBAN</value>
      <webElementGuid>e988c6a2-0f1a-4087-9be3-26378d32f033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched is-invalid</value>
      <webElementGuid>51209b66-4a8d-4572-a8d1-863288496c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transferFromIBAN&quot;)</value>
      <webElementGuid>67dd015f-f9f7-4ce7-b022-dbf1a35a0bc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transferFromIBAN']</value>
      <webElementGuid>d35f136d-960b-40c8-851a-9e4d47e95919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/div[3]/div/input</value>
      <webElementGuid>f2f581d2-f79f-45a8-87d8-c31c40e8e639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[4]/div/div[3]/div/input</value>
      <webElementGuid>6f0b76f0-bbc7-4a2b-80b7-c88c97df9f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'transferFromIBAN']</value>
      <webElementGuid>0cb3992b-fd7d-43e2-a12d-b6942edcd1fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
