<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__arName</name>
   <tag></tag>
   <elementGuidId>50614637-607a-4029-a62b-f253f30b45eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='arName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cb1d49b-b26d-4ef0-8b74-4c9ca8effa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>arName</value>
      <webElementGuid>bea470a5-a2cd-4495-b817-c70e787c1401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arName</value>
      <webElementGuid>a092d0df-c052-484a-9583-f9396a6b573b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>arName</value>
      <webElementGuid>4e90bf23-d913-4094-980d-84c8c2b5d55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>49f8b927-0f98-4e8c-87ac-d6c63b8b3c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arName&quot;)</value>
      <webElementGuid>d37254d5-602d-4545-97ca-cd2301b5eca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='arName']</value>
      <webElementGuid>bef51e9b-5b21-42ee-a071-f966a9aa4025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/div/div/input</value>
      <webElementGuid>4a900deb-cead-4391-a3b2-67c80ab33524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[2]/div/div/div/input</value>
      <webElementGuid>5825bbed-2f66-4576-a028-297e4ca28acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'arName']</value>
      <webElementGuid>f0e6128a-cd55-4d1f-a146-76618d903f5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
