<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__receiverEnglishNameLikePassport</name>
   <tag></tag>
   <elementGuidId>3b6c34f8-fcdc-46b2-86f9-cd9e9b4610b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receiverEnglishNameLikePassport</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='receiverEnglishNameLikePassport']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b780431-595d-4267-9aaf-ba602eafbca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>receiverEnglishNameLikePassport</value>
      <webElementGuid>a052a98a-904f-42bb-aa26-8a2a1fb8e4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receiverEnglishNameLikePassport</value>
      <webElementGuid>eddb1ad9-49f6-47a4-8261-07b4f02c223a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>receiverEnglishNameLikePassport</value>
      <webElementGuid>d3debf92-ad12-42bd-aec1-ea8cf3e5d135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3399009e-acc7-4a46-b832-8382ba0c2d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receiverEnglishNameLikePassport&quot;)</value>
      <webElementGuid>bf6eb041-496c-49ac-8550-6b8db088d0d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='receiverEnglishNameLikePassport']</value>
      <webElementGuid>702288df-f9fb-44d2-b493-a5d6d6f41a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/div/div[2]/div/input</value>
      <webElementGuid>88df603d-5b0d-45e0-8a15-f13315a3cf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/div/div[2]/div/input</value>
      <webElementGuid>6c01d59c-0004-4d92-9c99-5f34eb6129d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'receiverEnglishNameLikePassport']</value>
      <webElementGuid>bbcc6504-5742-4726-8c58-fc929a5cab87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
