<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__enName</name>
   <tag></tag>
   <elementGuidId>6578838b-5253-4d58-87ef-085acd6a6ced</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='enName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>febefb25-4fff-4c38-b3fc-3d0f069369b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>enName</value>
      <webElementGuid>dcf033d0-dd4e-4c54-b869-1ab5e1ed6c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enName</value>
      <webElementGuid>615d51ed-9fcd-4db1-b631-c58de936fdaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>enName</value>
      <webElementGuid>cb5a6637-6eb6-4214-a10a-68463ec9cef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>71116f7f-d449-49b2-a481-4759a6238f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enName&quot;)</value>
      <webElementGuid>3b940218-ad39-4b71-be5d-c341ca9ab2bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='enName']</value>
      <webElementGuid>3ce537a1-0169-49d5-8c83-5be5f400d4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/div/div[2]/input</value>
      <webElementGuid>89f12fda-1fc9-4835-b955-996f435cfc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[2]/div/div/div[2]/input</value>
      <webElementGuid>5fce9a4a-bcd8-433b-8349-46c04c14c1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'enName']</value>
      <webElementGuid>2828c606-575a-4378-a558-8ed8b451d853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
