<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__currencyTransferTransactionAmount</name>
   <tag></tag>
   <elementGuidId>947af652-7376-429c-89e3-4472f71e0165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currencyTransferTransactionAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='currencyTransferTransactionAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36edcc33-26dd-42ce-85bd-f5d3a0f7de07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>currencyTransferTransactionAmount</value>
      <webElementGuid>fbbe4be7-004e-48cf-99b5-e97ab5e3b60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currencyTransferTransactionAmount</value>
      <webElementGuid>59825629-2154-4ac0-8ac4-d84061a901b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>currencyTransferTransactionAmount</value>
      <webElementGuid>371935ce-0b2f-47a9-8a73-a7e1c5926d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d23bd54e-1573-4b55-8dfd-ec985e062663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currencyTransferTransactionAmount&quot;)</value>
      <webElementGuid>699a46e0-39ce-4a54-87ea-321f40a5c681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='currencyTransferTransactionAmount']</value>
      <webElementGuid>726d7824-dc7c-471e-b8ce-d43aa722052a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/div/div[2]/input</value>
      <webElementGuid>ebac7bf4-d8a9-4536-84c7-175a4fab3ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[4]/div/div/div[2]/input</value>
      <webElementGuid>2054d8c2-130f-4495-959d-e9801558eab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'currencyTransferTransactionAmount']</value>
      <webElementGuid>d17aa4f7-1a53-4095-9649-7af89cf2861d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
