<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__receiverJobTitle</name>
   <tag></tag>
   <elementGuidId>fa645142-163b-4438-9c04-04187f9ebc1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receiverJobTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='receiverJobTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>079a0c2a-0b87-44f9-88fd-0cc3c089f074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>receiverJobTitle</value>
      <webElementGuid>cf08aa3c-def6-4863-b663-125c220f531c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receiverJobTitle</value>
      <webElementGuid>6e5f5bd2-2c8b-4d86-b2c5-95eb9fef464e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>receiverJobTitle</value>
      <webElementGuid>c3e62f99-4856-41ea-b521-bd1fee24c46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9c01996e-6997-4745-8e49-86788b3ca579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receiverJobTitle&quot;)</value>
      <webElementGuid>bcf6fb71-165e-42c1-ae5a-dd741bd530dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='receiverJobTitle']</value>
      <webElementGuid>b8259e3a-402a-42ba-a369-8eceba538cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/div/div[3]/input</value>
      <webElementGuid>a2e0653d-1b45-46a2-b82b-cd82bc823e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/div/div[3]/input</value>
      <webElementGuid>4cc669ed-7adf-4b8c-9972-06f531c126f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'receiverJobTitle']</value>
      <webElementGuid>0c748802-b06f-448a-ab48-e9cefbb8b0f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
