<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__oldLicenseFullSerial</name>
   <tag></tag>
   <elementGuidId>aa897586-57d5-4bf7-991b-ec796811a09f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#oldLicenseFullSerial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oldLicenseFullSerial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05c81b2d-5a98-45b5-97c0-d07bd04b2c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>f853d577-6818-4379-b026-4f21188dfc21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>eb79809d-6131-4979-8d96-31ebc73e39ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>7fa65e3d-de5f-4391-a2e5-1a89eb1c35ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3acd4be7-3b9b-42c1-8de1-e6881123cf51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldLicenseFullSerial&quot;)</value>
      <webElementGuid>b60c7e59-0840-4cb3-b7da-8e6ada709a85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oldLicenseFullSerial']</value>
      <webElementGuid>69fed197-e8e1-466b-9ff4-d763e6fea20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div/div[3]/div/input</value>
      <webElementGuid>1e62c03a-b2c1-4042-8383-55e8d2d9ede0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>27f90fdd-b6ba-41a0-8060-f0a9ab24603c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'oldLicenseFullSerial']</value>
      <webElementGuid>60af5039-00a0-4fe1-8119-63326334eeab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
