<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__projectImplementationPeriod</name>
   <tag></tag>
   <elementGuidId>0549e3ce-1a09-473e-bd6b-1ddc19975168</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#projectImplementationPeriod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='projectImplementationPeriod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff2d5826-6556-4b99-9899-39e9b52493d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>projectImplementationPeriod</value>
      <webElementGuid>d55ac370-45a6-45cc-bb54-0943ee22dd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>projectImplementationPeriod</value>
      <webElementGuid>17340bee-f76d-48fc-b2a9-966ad50edc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>projectImplementationPeriod</value>
      <webElementGuid>d88f25ce-2568-4bef-91f2-7ebd22761d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2cdc4845-d7b1-4c5b-94ab-06ac298c8d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projectImplementationPeriod&quot;)</value>
      <webElementGuid>07c3e9c4-1efc-4e27-832a-0b51295c9a25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='projectImplementationPeriod']</value>
      <webElementGuid>c73df793-cfca-4b8b-a7e2-af1d12a07f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/div[2]/div[3]/input</value>
      <webElementGuid>808fb50f-7978-4cf7-9278-25c73a3e17a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/div[2]/div[3]/input</value>
      <webElementGuid>85bb6f35-7cfc-42c4-922f-26c44c6c4c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'projectImplementationPeriod']</value>
      <webElementGuid>5884c182-f72d-4b87-be3a-55b061b3848a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
