<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__qatariTransactionAmount</name>
   <tag></tag>
   <elementGuidId>d696c47a-654c-416d-a09f-8458eac8b514</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qatariTransactionAmount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='qatariTransactionAmount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6920d403-f19a-4c35-bba9-86b495cee718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>qatariTransactionAmount</value>
      <webElementGuid>8bd4f955-3d2f-4537-a46a-505480f0e39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qatariTransactionAmount</value>
      <webElementGuid>7f430058-c09e-4b65-9350-6fb58ac144b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>qatariTransactionAmount</value>
      <webElementGuid>90d09aba-4166-48c2-bdd5-75208ff1dbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>160b839a-419b-4fec-8141-481d3071d2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qatariTransactionAmount&quot;)</value>
      <webElementGuid>b9321945-6069-43ec-be76-a5964e358b4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qatariTransactionAmount']</value>
      <webElementGuid>e641366d-f2b8-4e3b-9b28-cf7872ad0641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/div/div/input</value>
      <webElementGuid>55c8e457-bf11-4137-8624-f7fe032ae638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[4]/div/div/div/input</value>
      <webElementGuid>ef670e96-8949-44f9-95be-f948252dd1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'qatariTransactionAmount']</value>
      <webElementGuid>67b7f5d2-008d-4e8b-9934-814d5db4733f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
