<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__transferringEntityName</name>
   <tag></tag>
   <elementGuidId>76717222-1bde-462f-a1a4-e53ec7e73b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transferringEntityName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transferringEntityName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4caaf820-7645-4a68-812a-20cc9c1bd360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>transferringEntityName</value>
      <webElementGuid>a3110c7d-ef12-49df-a710-29ed6862b2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transferringEntityName</value>
      <webElementGuid>42ac0ab2-0f09-439b-936c-99a4a8f34a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>transferringEntityName</value>
      <webElementGuid>a58b5442-85f0-4be8-8466-d08e7350c127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>371e4ba4-9f13-4f5b-8fbe-43583fcac73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transferringEntityName&quot;)</value>
      <webElementGuid>a259c21b-efdd-44e8-a44c-eaf4e2ae3577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transferringEntityName']</value>
      <webElementGuid>7e1db04a-4193-49e0-ba70-87762fb2567e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/div[2]/div[2]/input</value>
      <webElementGuid>5ae8a192-c2ac-4fa6-bda0-94f5178bb5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[4]/div/div[2]/div[2]/input</value>
      <webElementGuid>f80bb3d7-7a8b-4681-8913-cf0fc85e6af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'transferringEntityName']</value>
      <webElementGuid>bb26eec8-5ce1-4b38-bc47-ac7ab83c6d67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
