<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__totalCost</name>
   <tag></tag>
   <elementGuidId>e638a0ed-f062-489a-b8ba-c508d71fbaa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#totalCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='totalCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a229e5bd-337c-40fd-b581-9f8348e7ee40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>totalCost</value>
      <webElementGuid>640194b4-85b4-46df-adb1-fc3368b20dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalCost</value>
      <webElementGuid>156ade1d-45e6-41c4-84c2-24fe8bbfec67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>totalCost</value>
      <webElementGuid>16897118-21b7-4799-bf98-d59bea02dff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e208b3cc-068a-467e-93ae-b728eb0e38c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalCost&quot;)</value>
      <webElementGuid>02fcc448-70b9-4a02-b339-b811baf5827a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='totalCost']</value>
      <webElementGuid>c16c86a1-81f9-4947-b4be-6af95527225a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/div[3]/div[3]/input</value>
      <webElementGuid>ac25c6eb-d70e-487f-bd17-7e505efecc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>03cf7f98-fa1e-41fa-9a5a-eda2b8a912a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'totalCost']</value>
      <webElementGuid>156a8b39-5fdf-4d62-ac4c-1e7e7ac7238f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
