<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__projectName</name>
   <tag></tag>
   <elementGuidId>91ac6919-1f6e-4e8f-8497-a3e2da7b561f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#projectName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='projectName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2d4521fc-6977-429a-83e6-7151db0f21ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>projectName</value>
      <webElementGuid>11fc6eac-6aef-44bd-aff8-3748a7776aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>projectName</value>
      <webElementGuid>9f05aab3-3310-47de-bc74-e24ff41dc6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>projectName</value>
      <webElementGuid>48b766d9-3484-4ad2-9ca3-740bbfc51da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>af867673-5c59-4279-b428-c5766c6195a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projectName&quot;)</value>
      <webElementGuid>c41886f5-d9fb-42c6-bafe-952aa372aa9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='projectName']</value>
      <webElementGuid>3db8d80d-881a-42fc-87d0-ef0c098e9593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/div[2]/div/input</value>
      <webElementGuid>e0123832-b1d3-46aa-a269-4b46ed750293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/div[2]/div/input</value>
      <webElementGuid>dd3da346-177b-4af2-8a69-5d06b2048c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'projectName']</value>
      <webElementGuid>5e1431cd-40cc-4adf-90b5-acc7cd69b936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
