<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__transfereeIBAN</name>
   <tag></tag>
   <elementGuidId>4f845e88-87e3-40e8-90a6-701522b8eda3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transfereeIBAN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transfereeIBAN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9acd9f2d-7916-487d-b24c-026a100d29c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>transfereeIBAN</value>
      <webElementGuid>c925d258-a872-42e7-b33a-6e7fce9b3296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transfereeIBAN</value>
      <webElementGuid>86bb59da-df02-4037-af8a-7232d4edc214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>transfereeIBAN</value>
      <webElementGuid>bd443d92-ff5b-4bdc-83e7-c7306b24ecd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>97e19b1a-a69b-48ae-bb4f-1c58715855b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transfereeIBAN&quot;)</value>
      <webElementGuid>790de9f5-33ff-42cb-b608-ee76e70d982f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transfereeIBAN']</value>
      <webElementGuid>33441d15-d6a2-44bb-91d3-a191637d82f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/div[3]/div[2]/input</value>
      <webElementGuid>c5ea1dbc-1370-4959-bec4-c98fb9e208d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[4]/div/div[3]/div[2]/input</value>
      <webElementGuid>e51ddcf5-c978-4349-b5ea-bc38201c7a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'transfereeIBAN']</value>
      <webElementGuid>51b09348-d4d8-4a1c-9a1c-1cd08f77b9b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
