<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__receiverNameLikePassport</name>
   <tag></tag>
   <elementGuidId>f81454b2-680a-48b2-a65c-688ec87e696e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receiverNameLikePassport</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='receiverNameLikePassport']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92dcde6e-0f52-430f-b1e5-608ceb106dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>receiverNameLikePassport</value>
      <webElementGuid>5b82f0e2-bbe0-40d7-9a9b-ab08dc39786d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receiverNameLikePassport</value>
      <webElementGuid>b9422cff-fe9c-410b-b8ce-1706375e21d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>receiverNameLikePassport</value>
      <webElementGuid>370bf555-de69-48b8-b325-b854edf70f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>5a33f2b8-39e2-4291-878a-3cbe3d6ff07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receiverNameLikePassport&quot;)</value>
      <webElementGuid>fdaec619-4243-4cd4-823a-177f4df1ee2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='receiverNameLikePassport']</value>
      <webElementGuid>5c2fbf10-c5dd-4693-ac77-680948104d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/div/div/div/input</value>
      <webElementGuid>a9e7e2a6-3d09-476f-8952-ae6b0733c7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/div/div/div/input</value>
      <webElementGuid>8100a192-260e-4e6d-827e-4cc71e77d2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'receiverNameLikePassport']</value>
      <webElementGuid>8a395647-f22e-4eb8-b051-fedda10cd48c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
