<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__receiverIdentificationNumber</name>
   <tag></tag>
   <elementGuidId>606fcd82-3514-41e5-b09b-06d3163fd2db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#receiverIdentificationNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='receiverIdentificationNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dd2012d-71fe-4e65-8430-b52f0e2daad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>receiverIdentificationNumber</value>
      <webElementGuid>75692661-9d60-43e1-843e-bef7bda45563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>receiverIdentificationNumber</value>
      <webElementGuid>0d83ee63-3d03-4fae-a78b-04bc2b04f5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>receiverIdentificationNumber</value>
      <webElementGuid>24f9fb4b-671b-4147-bc0e-440e4686b230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>4ca8ad87-62a0-46c3-a311-ea200dfbca6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;receiverIdentificationNumber&quot;)</value>
      <webElementGuid>b3ad89f9-3c65-4f98-8dff-98137301a557</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='receiverIdentificationNumber']</value>
      <webElementGuid>e9d4d3af-3b31-4dac-8f63-aeedda525957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/div[2]/div[2]/input</value>
      <webElementGuid>93be1160-df8b-4373-8477-50b87b147990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/div[2]/div[2]/input</value>
      <webElementGuid>38063539-0a2b-4704-8deb-06ea7c1f6ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'receiverIdentificationNumber']</value>
      <webElementGuid>b682c528-1759-405f-945c-b9176ee5ef0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
