<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__isConstructional</name>
   <tag></tag>
   <elementGuidId>609bfa80-4683-4e7f-8a78-b64a76e52ce7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isConstructional</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isConstructional']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b27c5a61-3bb5-4a55-939c-9a645cda12a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5358629f-8117-498c-ac12-8d3c84ad21d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isConstructional</value>
      <webElementGuid>b9112f98-2918-4c29-b247-e16c9a6db066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isConstructional</value>
      <webElementGuid>1fe76798-adf1-4381-83da-ad8844a4066e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>dd1d277b-7e96-4683-8d02-9577f80c1f26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isConstructional&quot;)</value>
      <webElementGuid>0ff13592-55d6-47dc-9707-5d6f12e27c42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isConstructional']</value>
      <webElementGuid>e35ac1f0-81e8-4793-a231-63882ea10228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/fieldset/div/div[2]/div/input</value>
      <webElementGuid>4067185f-51d7-4078-83de-135117ec9f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/div/input</value>
      <webElementGuid>e9e03a61-5ef7-4727-ac4b-2e271859fcd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'isConstructional']</value>
      <webElementGuid>858f365d-8656-4a37-9b44-d2049b9282e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
