<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__directBeneficiaryNumber</name>
   <tag></tag>
   <elementGuidId>802354b9-3480-4cf5-95fa-ad33cadba43f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#directBeneficiaryNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='directBeneficiaryNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd090360-7909-41db-bc78-40ad78af4db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>directBeneficiaryNumber</value>
      <webElementGuid>0ad477ad-deb9-4b80-bac7-ee73cdeaf2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>directBeneficiaryNumber</value>
      <webElementGuid>26df57b4-e0c6-4abc-af57-f91f97f1e2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>directBeneficiaryNumber</value>
      <webElementGuid>f6336e20-ab9e-4d9c-b1b4-fe38b426453e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>142d3ca3-8d93-45b5-8a5f-ecb9eca080f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;directBeneficiaryNumber&quot;)</value>
      <webElementGuid>4a176ff7-ca3c-41ce-a88d-d621416ac62b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='directBeneficiaryNumber']</value>
      <webElementGuid>fcfbc050-32fe-475e-869a-9143b9069fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[2]/div[2]/input</value>
      <webElementGuid>638cdd73-f7f8-4e12-aed9-bb6331bcbf32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/fieldset/div[2]/div[2]/input</value>
      <webElementGuid>05dbcc04-3cb9-4a8b-9005-2fcdc6006a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'directBeneficiaryNumber']</value>
      <webElementGuid>38d5be07-a68c-4035-8fb2-f6db17edf91c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
