<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__thirdSDGoalPercentage</name>
   <tag></tag>
   <elementGuidId>ffa99e11-9830-42e4-a7c7-6723757be710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#thirdSDGoalPercentage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='thirdSDGoalPercentage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b0118df-7500-4120-981f-93e38a3d6d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>thirdSDGoalPercentage</value>
      <webElementGuid>207264de-dc70-48a9-bb22-1b4ce1e20354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>thirdSDGoalPercentage</value>
      <webElementGuid>2508d790-7eb2-4b7f-85ab-6661b47d8054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>thirdSDGoalPercentage</value>
      <webElementGuid>22aa13d2-fa4c-42d5-99f0-0b7edd962268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>4c71677d-a161-407c-a278-7d89b88f57e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;thirdSDGoalPercentage&quot;)</value>
      <webElementGuid>21e7485d-28d0-4c8b-8ab2-3f9d2928d25b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='thirdSDGoalPercentage']</value>
      <webElementGuid>953e3eab-e4a4-4857-891f-1cb65149a4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/fieldset[2]/div/div/div[3]/div/input</value>
      <webElementGuid>9323d66b-1fc0-41fa-9242-1936945e85f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>a22fa214-95c1-4cc0-8081-4d3b71193c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'thirdSDGoalPercentage']</value>
      <webElementGuid>650b2d5b-21a1-43f9-9e36-d5f9b4b40f31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
