<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__beneficiaries0to5</name>
   <tag></tag>
   <elementGuidId>b71df276-f787-4794-aad7-fa7f77ae2534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beneficiaries0to5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='beneficiaries0to5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3c19251-d0d3-40a7-bce0-a876132587a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beneficiaries0to5</value>
      <webElementGuid>a29e3f7e-6aab-4cd5-b734-bcf8c6580dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>beneficiaries0to5</value>
      <webElementGuid>ca0d39cd-78cb-4a3a-9f37-735cac27eb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>beneficiaries0to5</value>
      <webElementGuid>55b7e0a0-119e-443d-afa6-7725168909dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>66e4ba90-01be-45df-877f-a7d9ec3cee5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beneficiaries0to5&quot;)</value>
      <webElementGuid>80785101-ac19-44d3-abb0-17e53f53f3ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='beneficiaries0to5']</value>
      <webElementGuid>66c83c75-4db5-41ca-9ce3-889c8cbccaca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[4]/div/div/div/input</value>
      <webElementGuid>84dbf9ab-0bc8-4f6e-9bfe-0969ecea6211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>af014b83-2f8b-4b44-8114-440b02d3f436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'beneficiaries0to5']</value>
      <webElementGuid>8adf6b59-650d-4108-a225-998753fa6fb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
