<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__beneficiariesOver60</name>
   <tag></tag>
   <elementGuidId>e7a11b33-a718-47e8-bce8-b2efed2d1f69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beneficiariesOver60</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='beneficiariesOver60']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff4190d2-7675-4620-8af0-f7844658d763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beneficiariesOver60</value>
      <webElementGuid>503c43df-900d-4bca-b350-05c487ccc32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>beneficiariesOver60</value>
      <webElementGuid>0db09e56-4f03-4145-a03f-f3a50fb73e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>beneficiariesOver60</value>
      <webElementGuid>5d1bf863-2472-40be-8e4f-3313d8a1dc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>715fac68-8675-4fb3-b7d3-82c9cabcfdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beneficiariesOver60&quot;)</value>
      <webElementGuid>0280b284-0917-41f9-87fa-a1e97ede611f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='beneficiariesOver60']</value>
      <webElementGuid>17b55707-061b-4d24-8728-c4bc8e98f6e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[4]/div/div/div[4]/input</value>
      <webElementGuid>5fce6b71-cb89-43e6-a74a-ac26aa6ef31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[4]/input</value>
      <webElementGuid>a4755a72-aa96-4a75-8454-17be4746234f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'beneficiariesOver60']</value>
      <webElementGuid>096a9430-e56b-4568-8a7f-4b780c8feb73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
