<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__indirectBeneficiaryNumber</name>
   <tag></tag>
   <elementGuidId>6e21bfe8-844f-4b15-a6f8-c5ee8af75e72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#indirectBeneficiaryNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='indirectBeneficiaryNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18f3bba7-46aa-469a-93f8-8990a5e22cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>indirectBeneficiaryNumber</value>
      <webElementGuid>6410cfc5-e1f4-42c9-841e-166cca50d197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>indirectBeneficiaryNumber</value>
      <webElementGuid>23e223b3-042e-42bf-b5a0-f4f536709382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>indirectBeneficiaryNumber</value>
      <webElementGuid>eb35bdbe-f479-4ae0-a66e-eff8a428cc76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>31b096ab-7037-40c9-a80d-66bd3acf2943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;indirectBeneficiaryNumber&quot;)</value>
      <webElementGuid>a485e169-7ef8-4d67-8fb2-a670fa90ef7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='indirectBeneficiaryNumber']</value>
      <webElementGuid>836df1d7-edf4-4bfa-9886-6aa96a4a9353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[2]/div[3]/input</value>
      <webElementGuid>530b975c-fb35-44a1-a23f-f03797602225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>4d23247b-8851-46fd-8f38-63c0139efbff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'indirectBeneficiaryNumber']</value>
      <webElementGuid>82f13bf5-a85b-45d4-a964-8c163084b441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
