<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__beneficiaryFamiliesNumber</name>
   <tag></tag>
   <elementGuidId>0d34f7ed-c099-408a-9724-06c5e01ccbbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beneficiaryFamiliesNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='beneficiaryFamiliesNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fa7c47a-edd4-4f91-8ccf-01db8501df96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beneficiaryFamiliesNumber</value>
      <webElementGuid>a446f75b-c6f4-4e1e-b48e-2b347acecacc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>beneficiaryFamiliesNumber</value>
      <webElementGuid>d79ec716-5bdc-4468-862f-e2153a32eda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>beneficiaryFamiliesNumber</value>
      <webElementGuid>871bf8af-a898-4874-9402-9c957845002b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ec9b0e8b-c1db-42cd-969c-8d95a69b854b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beneficiaryFamiliesNumber&quot;)</value>
      <webElementGuid>1544f071-176a-45e9-aa76-497c3102f95b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='beneficiaryFamiliesNumber']</value>
      <webElementGuid>c576b796-598c-46e9-8b7f-36c5c49ccc8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[2]/div[4]/input</value>
      <webElementGuid>b6fd1a85-e4b5-4b6f-9e4c-7ba2e69a7976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>9825cf30-e46e-4d5c-a930-a12f6fbc2fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'beneficiaryFamiliesNumber']</value>
      <webElementGuid>237e3073-aec6-4837-a905-f97bb6bb3a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
