<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__percentage</name>
   <tag></tag>
   <elementGuidId>3fa461a2-0d66-4d23-8e48-05d85baa0a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#percentage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='percentage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc5bd9b8-a425-4f37-a947-8e3902385d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>percentage</value>
      <webElementGuid>0f0b2d53-3f4f-4200-9888-1bf1491e408d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>percentage</value>
      <webElementGuid>5b9a5f35-220f-4654-8d48-cce915ef88d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>percentage</value>
      <webElementGuid>925f2a62-e285-4157-a999-3aaf6538cfb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>43a7e5d8-1ae2-4596-a857-e253d6cdf1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>135e0682-0ebf-4c27-ab15-9421a8e252cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2ce9834d-3d4c-4eb3-8d24-86cbbe192ec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;percentage&quot;)</value>
      <webElementGuid>35ea8c8e-5d49-4dda-a71e-b34b7932d87d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='percentage']</value>
      <webElementGuid>bee86a69-b27a-461e-b3cb-9c10e690e3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[5]/div/fieldset/div[2]/div[2]/input</value>
      <webElementGuid>311dee8a-7a88-4396-87fd-aa2a1b10183a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[5]/div/fieldset/div[2]/div[2]/input</value>
      <webElementGuid>a6f0f152-c20f-46b4-9d8b-70301e5ce0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'percentage']</value>
      <webElementGuid>a93124f0-394d-4219-897f-34e185853eaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
