<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__projectName</name>
   <tag></tag>
   <elementGuidId>b0f2568c-1075-4389-b5f8-0a924cf2f286</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#projectName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='projectName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38d64eb3-bc45-4066-812e-25cb200d38a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>projectName</value>
      <webElementGuid>ba5ce6c4-274f-4887-8bd3-74dfb575fa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>projectName</value>
      <webElementGuid>a3796dfd-23b6-4701-9370-18fe3a837f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>projectName</value>
      <webElementGuid>22b798a4-47d1-4cf6-a96f-c573b5785690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>906a26b9-0a7f-4df0-be2b-a50c5f34a932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projectName&quot;)</value>
      <webElementGuid>e4be63d3-67c8-46f7-832c-f68ca811d5a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='projectName']</value>
      <webElementGuid>74810827-da9d-4302-87d5-f83e68bcedbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/fieldset/div[2]/div[2]/input</value>
      <webElementGuid>49fd636e-8852-4527-9831-742ddc9acc6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div[2]/input</value>
      <webElementGuid>2a595ba8-7b19-455c-85a1-f2115d0b7d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'projectName']</value>
      <webElementGuid>a6ab9866-417c-4637-94fd-751e4669a2e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
