<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__executionRegion</name>
   <tag></tag>
   <elementGuidId>6617b1c0-6a09-49a9-8359-2f85917bdf72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#executionRegion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='executionRegion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1847df56-fdd5-41f0-8758-4f11cebac09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>executionRegion</value>
      <webElementGuid>f02d499e-bac1-4ea5-96f2-b1dca8399424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>executionRegion</value>
      <webElementGuid>188d0029-ef43-4059-a7cb-6f5808fed6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>executionRegion</value>
      <webElementGuid>cbd322e9-d447-4c4a-bdef-3a0c01abe1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>339a0ec6-755c-427b-804f-756a006b4d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;executionRegion&quot;)</value>
      <webElementGuid>e5c7c596-fbe3-4cb5-8cd4-047ec2664ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='executionRegion']</value>
      <webElementGuid>39c383db-228a-459a-bf02-932b52fd146b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/fieldset/div[5]/div[3]/input</value>
      <webElementGuid>92537ac0-e90b-44bb-a4b3-cb28d89b8470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/input</value>
      <webElementGuid>7d3196c7-e7c8-47d8-82ba-947d13ca5d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'executionRegion']</value>
      <webElementGuid>2b8349f1-0144-431e-9d56-6027f9e07729</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
