<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__secondSDGoalPercentage</name>
   <tag></tag>
   <elementGuidId>1f3e1fe6-0d9e-4699-9b48-e4f658502944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#secondSDGoalPercentage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='secondSDGoalPercentage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9f8c621-88f6-40ba-a99a-de51a1106b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>secondSDGoalPercentage</value>
      <webElementGuid>358f199c-ab55-4737-bcf8-647a324009a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>secondSDGoalPercentage</value>
      <webElementGuid>0bf0dcb3-7f99-481a-a3b7-e9701a575f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>secondSDGoalPercentage</value>
      <webElementGuid>81142a4d-4bce-46c3-924c-2f46cdb87dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>99427be8-075a-4288-a838-37785e71f4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;secondSDGoalPercentage&quot;)</value>
      <webElementGuid>b3844f3f-66a8-49e4-bf63-4a424e825338</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='secondSDGoalPercentage']</value>
      <webElementGuid>0a5b4c48-7764-4157-80ec-2a1afe223e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/fieldset[2]/div/div/div[2]/div/input</value>
      <webElementGuid>3aa05adc-4d92-43c1-9089-ee81e84652c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/div[2]/div/input</value>
      <webElementGuid>d0b8a05a-4777-4b5e-a9fb-bf641910ae24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'secondSDGoalPercentage']</value>
      <webElementGuid>5eac9b56-5164-45ce-aca3-c4ecd7b5996e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
