<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__componentName</name>
   <tag></tag>
   <elementGuidId>9dc46f32-b650-4a48-856a-8f1b822de36e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#componentName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='componentName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>268bacfd-c097-4456-862f-901e0be9bc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>componentName</value>
      <webElementGuid>7863bb6f-4337-4592-9e57-3ef4ddbbc3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>componentName</value>
      <webElementGuid>b31e093e-2569-475b-8139-77fc67c60256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>componentName</value>
      <webElementGuid>65ab3e8a-d5f3-4a23-a754-fe79dc381999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>6a61f5d3-4140-409c-9868-130ccbbc0a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>86f364c0-b2bb-41ee-9fbe-40b342f80d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;componentName&quot;)</value>
      <webElementGuid>4ecd6abd-8af7-475e-96ac-2cd75e0f8287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='componentName']</value>
      <webElementGuid>d7419e0e-aeef-48f3-89a4-4b5ce1d71348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/fieldset/div[2]/div/input</value>
      <webElementGuid>b76539e4-d725-4bdf-a670-df1864fd3c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[4]/div/fieldset/div[2]/div/input</value>
      <webElementGuid>f3f9250d-ab97-4b23-a615-053017840f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'componentName']</value>
      <webElementGuid>4c338784-1951-419b-a4fd-a89fb30cc760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
