<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__beneficiaryRegion</name>
   <tag></tag>
   <elementGuidId>e36556a0-ba20-4bb2-a7d5-7951e4f9e596</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beneficiaryRegion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='beneficiaryRegion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ec37391-bdc8-4308-9ad3-1f7a2d9d3824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beneficiaryRegion</value>
      <webElementGuid>d04d5941-0b43-44ec-9a1a-2ec745897071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>beneficiaryRegion</value>
      <webElementGuid>3433bf5f-17d6-4ee6-8590-2ff64d459b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>beneficiaryRegion</value>
      <webElementGuid>a300bec3-eb16-43e0-9864-492bddfd3fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>4041d4b0-9feb-4301-a4e1-f893af691477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beneficiaryRegion&quot;)</value>
      <webElementGuid>5f2bd3b9-5447-42d4-be96-aa384ce47c1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='beneficiaryRegion']</value>
      <webElementGuid>76c61010-b44e-43a2-98f5-79b35eda2ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/fieldset/div[4]/div[3]/input</value>
      <webElementGuid>5ac9fbd0-406c-4549-9c46-97ac6f417865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>d457fd2d-276b-47a8-866d-441f97943dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'beneficiaryRegion']</value>
      <webElementGuid>57b729dc-db24-4cdc-97aa-104f34503ca0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
