<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__firstSDGoalPercentage</name>
   <tag></tag>
   <elementGuidId>2f1ef451-3f11-4b03-b7e9-f5f1812982bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstSDGoalPercentage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstSDGoalPercentage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b509c51-4439-41cd-94aa-9184b74ab63f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstSDGoalPercentage</value>
      <webElementGuid>bf734bfb-467a-4d56-a1e4-d4755c9471e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>firstSDGoalPercentage</value>
      <webElementGuid>af1ecfdc-8148-452e-90a1-08eb749048ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>firstSDGoalPercentage</value>
      <webElementGuid>ca3b7ed2-b164-4116-8e98-cee7e3a2b2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c7c1ace9-3a2f-42cd-b955-29871432cd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstSDGoalPercentage&quot;)</value>
      <webElementGuid>1b8f6612-0c4d-4ae5-9385-1a9354de7dc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstSDGoalPercentage']</value>
      <webElementGuid>03276dcf-daf2-4e8f-8e9f-0c91127e7acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/fieldset[2]/div/div/div/div/input</value>
      <webElementGuid>263f57c0-9aef-4887-abca-08b3af17731f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/div/div/input</value>
      <webElementGuid>ac432e7e-f043-4409-be56-2bdcf4654511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'firstSDGoalPercentage']</value>
      <webElementGuid>4f5b679b-4746-4ea5-bb1c-6c0fffdebda9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
