<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__totalCost</name>
   <tag></tag>
   <elementGuidId>749a3f03-3937-4244-87b6-8c67c57dfec9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#totalCost</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='totalCost']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c590f87f-c2da-4147-a711-b48982a7cd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>totalCost</value>
      <webElementGuid>1bd2b6c1-c425-4dab-be71-11ba13fbb1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>totalCost</value>
      <webElementGuid>d2208f8d-c196-4ef4-8859-86d286474c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>totalCost</value>
      <webElementGuid>8413acc6-660e-436a-b5ff-2401a4843258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>65cdb1f3-b8f7-4a51-aadb-a79e6dd981c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>a61f7eb8-100e-4f44-8100-0cddc6f2a04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;totalCost&quot;)</value>
      <webElementGuid>655bf6b9-4f3b-4945-bdfd-40bdd4133bd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='totalCost']</value>
      <webElementGuid>a244ca42-e27e-4315-a6f2-f9d1c5a5682f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/fieldset/div[2]/div[3]/input</value>
      <webElementGuid>c7d893b3-6c46-4558-aa41-cf49ecb22c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[4]/div/fieldset/div[2]/div[3]/input</value>
      <webElementGuid>a4594bf8-7f81-4791-a3c1-f5f3d19f90c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'totalCost']</value>
      <webElementGuid>74300bf1-c401-4d41-a736-e1d421aee9ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
