<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__beneficiaries19to60</name>
   <tag></tag>
   <elementGuidId>a1b3d1c1-ce25-444f-a53d-cfb2999e10e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#beneficiaries19to60</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='beneficiaries19to60']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>acb08777-4c7c-47bc-a904-dcfd133b32d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>beneficiaries19to60</value>
      <webElementGuid>502c6333-5480-4bcc-aa6a-119c0d39b601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>beneficiaries19to60</value>
      <webElementGuid>600f9dc2-97eb-4bfa-9f6e-89c0a2951337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>beneficiaries19to60</value>
      <webElementGuid>9eba58a4-ca76-42e5-884f-5f96ac8fb45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c3ae9911-d8f6-43b0-b009-542057afce45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;beneficiaries19to60&quot;)</value>
      <webElementGuid>88cb42f0-9cb8-4011-9cee-604bfb4e4893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='beneficiaries19to60']</value>
      <webElementGuid>938489e5-aeff-4e1d-adc2-549460a78270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[4]/div/div/div[3]/input</value>
      <webElementGuid>d1a1e28e-cfce-4663-b156-c5698059ca00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[3]/input</value>
      <webElementGuid>9626078c-353b-47cc-91dd-37fedcb51216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'beneficiaries19to60']</value>
      <webElementGuid>cd879aaf-2bdc-49a1-8c66-eed8afa0e739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
