<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__notes</name>
   <tag></tag>
   <elementGuidId>c1ee0c8f-a496-4f82-b6bb-9a0196072350</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca5e0fb9-8696-4550-bcac-b3d51e101a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notes</value>
      <webElementGuid>9f4e6e9b-c48d-4a10-b100-3db53ca585ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>notes</value>
      <webElementGuid>d408b5a5-7fbf-4da0-a58a-193857048b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>notes</value>
      <webElementGuid>c43ff73c-c28f-4a6f-97de-90e5476e48be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>7ccb7973-8e82-415f-a04f-5d7b3a3df24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>ee9e049d-dcb9-41e7-b04a-0e4cf3ec6951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notes&quot;)</value>
      <webElementGuid>aa7e74c0-c5c8-4b93-b111-530cabd684e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notes']</value>
      <webElementGuid>e770ad63-39be-41d8-92ed-d0e054069df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[5]/div/fieldset/div[2]/div[3]/input</value>
      <webElementGuid>23c10df6-18d8-4d08-9531-b7c72430c767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[5]/div/fieldset/div[2]/div[3]/input</value>
      <webElementGuid>0d2d89e8-779f-4e24-b861-d9acfff706d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'notes']</value>
      <webElementGuid>f5335f4c-56d3-45e5-882f-72850c290849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
