<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__templateSerialControl</name>
   <tag></tag>
   <elementGuidId>cec8ee10-5e21-433d-ab28-df9f12a58734</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#templateSerialControl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='templateSerialControl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1c3ae9a-dcb7-47c7-b50b-7c572e8b08d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>templateSerialControl</value>
      <webElementGuid>9f75ec0c-6721-48f4-a50a-10041c25a6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>e672a43d-3758-499e-9922-8ac1d7e81ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;templateSerialControl&quot;)</value>
      <webElementGuid>f4775baa-11e8-4c83-8bc2-526043ca45ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='templateSerialControl']</value>
      <webElementGuid>5c37d6b1-dd85-4119-9b84-2fdce08ae407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/fieldset/div/div[2]/div/input</value>
      <webElementGuid>629bef23-3b7c-4a48-8117-868940d4cdff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[2]/div/input</value>
      <webElementGuid>166bab0b-a857-4ef7-a4c3-34c53640c052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'templateSerialControl']</value>
      <webElementGuid>415775ae-2205-4101-8265-06650c2d1761</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
