<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__sustainabilityItems</name>
   <tag></tag>
   <elementGuidId>a3811cd2-1ce0-4128-86a1-288baec0d95e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sustainabilityItems</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='sustainabilityItems']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>505ffcc1-8ecf-4f3f-bfbc-b700bcfd8a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sustainabilityItems</value>
      <webElementGuid>d5d16ae7-67ff-4a3a-9a0f-b8dde038a685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>sustainabilityItems</value>
      <webElementGuid>eac0ed04-bfcb-4882-9d3d-55a5e0848e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>sustainabilityItems</value>
      <webElementGuid>44903f69-64b2-4c1b-aea6-e2c4f6707bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sustainabilityItems</value>
      <webElementGuid>72a9daf8-9003-43e8-a7c0-9ed749277e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f0c936b1-396a-49f7-bafb-e4499cd3bd2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b5130000-d76e-46ff-b292-db6723c1230d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>33bf04de-d324-4d25-9670-da0761da90a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sustainabilityItems&quot;)</value>
      <webElementGuid>ec9bc382-b057-4a21-a2ac-b62ad9bb6685</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='sustainabilityItems']</value>
      <webElementGuid>7527018f-807a-4166-a7a2-a92bfce10817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[10]/div/textarea</value>
      <webElementGuid>46d6e4d5-34f8-4f4e-8e40-937df7ecce32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/textarea</value>
      <webElementGuid>da6a65e3-4f5c-49b0-a0bd-3c99b46dedf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'sustainabilityItems' and @id = 'sustainabilityItems']</value>
      <webElementGuid>3d56ccab-8bb3-4c1b-b5e5-c81d77b8a9a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
