<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__expectedImpact</name>
   <tag></tag>
   <elementGuidId>0ecffa78-2cb7-4386-a987-e32a77146392</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expectedImpact</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='expectedImpact']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>583af6b4-5282-4915-92fa-eca1df97d6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expectedImpact</value>
      <webElementGuid>85527016-21cf-44e9-8441-0eb8ec5b4237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expectedImpact</value>
      <webElementGuid>236bb708-43cf-405a-92bb-7b74bcfd5798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>expectedImpact</value>
      <webElementGuid>6bd5bb0f-7dd3-421a-af1a-84f22149c63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expectedImpact</value>
      <webElementGuid>0e4f9b41-f0e3-4539-991a-07a6e969f2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9616467c-e32f-4755-a986-df2901d971a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>1660db78-9bbc-469e-8a21-b6bc14fb587d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>9d27e2be-8540-4d24-b8a6-3702e1f4b74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expectedImpact&quot;)</value>
      <webElementGuid>97784c47-8eee-479d-a62d-32eb347cfe78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='expectedImpact']</value>
      <webElementGuid>862cd520-5d20-4ae6-86a9-20af986dcb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[9]/div/textarea</value>
      <webElementGuid>eb4c5129-84e4-4c03-9500-85869d4abb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/textarea</value>
      <webElementGuid>3fd90b95-d531-40e8-b386-e092bfc2a459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'expectedImpact' and @id = 'expectedImpact']</value>
      <webElementGuid>8294e0f8-89a6-457b-b4ce-7af3acfed0d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
