<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__needsAssessment</name>
   <tag></tag>
   <elementGuidId>51e021c0-e98d-43bf-85e1-b478a6808393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#needsAssessment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='needsAssessment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6a929482-25a2-4d65-9fb6-9d61baa9f4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>needsAssessment</value>
      <webElementGuid>57397cce-03bf-41dc-85f3-4b1dbf276bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>needsAssessment</value>
      <webElementGuid>29e50265-1bf6-4528-ab95-81f3e5fb4cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>needsAssessment</value>
      <webElementGuid>7765165d-2ee9-4e44-8a6a-64fdf7e6213d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>needsAssessment</value>
      <webElementGuid>d1d43d36-5cbc-44be-8205-46053cbf6936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>0152be47-8641-4645-9801-2db8c54126dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>76fe9a1f-4701-40a0-9e6e-dc84d08ac571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>ad4b3335-26d7-410f-928d-c650bd8fac34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;needsAssessment&quot;)</value>
      <webElementGuid>c17686dc-c23f-47dd-9aa4-5f55573425e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='needsAssessment']</value>
      <webElementGuid>5dada97f-e10e-4886-a5ab-cb56890601cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[5]/div/textarea</value>
      <webElementGuid>ed99af5a-e8bd-4dc3-8849-b040b5f89deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/textarea</value>
      <webElementGuid>96548176-5e44-4869-b2d7-cd544c82ccd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'needsAssessment' and @id = 'needsAssessment']</value>
      <webElementGuid>ccfc72a4-f254-4f75-b50f-4805cdabb6c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
