<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__outputs</name>
   <tag></tag>
   <elementGuidId>236b88de-fdae-4504-a1e8-23ad18c5b656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#outputs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='outputs']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f7bded1c-f802-48a9-a7b5-c191a0e4fe2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>outputs</value>
      <webElementGuid>b2dc5a38-f3d6-43c5-9770-14923adcc22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>outputs</value>
      <webElementGuid>01cef483-233d-41d4-b91f-e3adb87e599f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>outputs</value>
      <webElementGuid>e9a44060-eafe-4609-abe3-db72f2287ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>outputs</value>
      <webElementGuid>b6a633ee-3687-496e-b094-f65eb95006fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d497e5f8-9821-48d7-b9c7-9386f7c1f2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d6d658a8-c065-428e-a9bc-ab82aabc793e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>73505fe3-16ef-4f84-b8c6-9c59341cb5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outputs&quot;)</value>
      <webElementGuid>1b218eb6-f5ef-442c-b7a6-2d2b3de8a1fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='outputs']</value>
      <webElementGuid>e2dc219c-e8c0-40f6-a208-b8f0ec27ab75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[7]/div/textarea</value>
      <webElementGuid>78ba73cc-dcd4-443e-8cf1-1127b3ed2741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/textarea</value>
      <webElementGuid>b5272d98-6560-42f4-a4d0-5f699703f01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'outputs' and @id = 'outputs']</value>
      <webElementGuid>be5c65b5-9809-420e-9fa7-79cb7a9566ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
