<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__goals</name>
   <tag></tag>
   <elementGuidId>313782b8-a594-4fc9-8d50-95d0de2c540f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#goals</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='goals']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d0823d17-3857-4835-b0f5-83a75793f6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>goals</value>
      <webElementGuid>31d85dba-f263-4515-b6ea-05181fba606a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>goals</value>
      <webElementGuid>98a630dc-a7bb-449c-b73a-aee6160e3597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>goals</value>
      <webElementGuid>5f943fe7-3d18-41d3-acf7-f0c815ef2e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goals</value>
      <webElementGuid>c877d58f-b9b3-4a6d-b269-a20dafa644ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4577777e-2389-4547-b766-b567c702459a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>0c985611-9b2d-4cfa-b18d-906767065a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>be170cc9-7fe0-4040-8913-a57fdb33ae81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goals&quot;)</value>
      <webElementGuid>c30fd167-8449-40e3-9322-2605f707c5ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='goals']</value>
      <webElementGuid>7f1462e5-d692-46c9-acfa-a028f10223fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div/div/textarea</value>
      <webElementGuid>e26f192e-90c0-4860-9ed9-1c2e36512bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab[3]/div/fieldset/div/div/textarea</value>
      <webElementGuid>83e0df35-b8e0-41ea-88c3-56a266055cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'goals' and @id = 'goals']</value>
      <webElementGuid>b451c4ad-40b5-494f-8646-deed5bcb7015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
