<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__successItems</name>
   <tag></tag>
   <elementGuidId>f28f2887-0cf1-4be1-be28-47b74e8b7ea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#successItems</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='successItems']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d864bb9b-d053-42d0-be2d-4be4f05b68d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>successItems</value>
      <webElementGuid>6e4d696d-c153-4987-a372-4113c84c1d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>successItems</value>
      <webElementGuid>c204ebf5-3a79-4b4f-b238-eef9dc94cb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>successItems</value>
      <webElementGuid>9aee17e4-fd6a-4556-8643-1c824dec58ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>successItems</value>
      <webElementGuid>2c901d3a-9b8a-45da-bbbd-7947e31da91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>03d26aee-63fc-497e-9c79-8a28067a1ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f7dc225d-bb00-495b-8916-82efb2245347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>3c8954d2-40a7-4489-bbf2-cecea8f05e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;successItems&quot;)</value>
      <webElementGuid>50c36ad2-80a9-45f7-b48c-b8e5098883e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='successItems']</value>
      <webElementGuid>e3f81590-bafd-4229-a031-c520cc9bc507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[6]/div/textarea</value>
      <webElementGuid>3fe4a785-ec9a-4485-a908-1199381f39d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/textarea</value>
      <webElementGuid>9dc5c475-4dcf-4153-9c1f-4a2ba7257d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'successItems' and @id = 'successItems']</value>
      <webElementGuid>a400ce9d-e9e0-4405-b5ac-9ae893b87ce0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
