<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__expectedResults</name>
   <tag></tag>
   <elementGuidId>beb9e97f-0e0b-4a5b-b7c9-6366b420a597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expectedResults</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='expectedResults']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>19efaaa8-dcea-4a1e-a93c-cf3cbc09fa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>expectedResults</value>
      <webElementGuid>50e68fd5-dc17-4aac-9715-fee8a4e2d473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expectedResults</value>
      <webElementGuid>f4fbf474-5df6-4264-97ed-088955e93e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>expectedResults</value>
      <webElementGuid>a2cc843b-c891-45a6-b077-f07555b61da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>expectedResults</value>
      <webElementGuid>ab1103c5-ffed-4685-b925-b1e8bb124635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>41a85369-a97e-47ac-bb73-927d7e559bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>a4dd79d9-1826-4e4f-8b27-f5725cbabd54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>f9e784e9-cad0-4b22-b39e-2d175079fb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expectedResults&quot;)</value>
      <webElementGuid>3685001a-f744-491c-aa14-2d259742b39c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='expectedResults']</value>
      <webElementGuid>835a1ba9-ad32-45c7-88b8-0cb675c9af65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/fieldset/div[8]/div/textarea</value>
      <webElementGuid>45fbdd84-373e-4664-88ef-f6cb47946094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/textarea</value>
      <webElementGuid>e63e8861-fd7c-44c2-9efe-99954d1e7d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'expectedResults' and @id = 'expectedResults']</value>
      <webElementGuid>4adecfc2-d82a-432e-82c5-f61169eb0922</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
