<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__projectDescription</name>
   <tag></tag>
   <elementGuidId>f239b79f-14b3-40ae-9a9b-8b61ebec8dfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#projectDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='projectDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ac2b8217-f4a6-4139-8944-980a3c64159e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>projectDescription</value>
      <webElementGuid>189a9a6f-e4df-4be7-9be7-b1b2dde35620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>projectDescription</value>
      <webElementGuid>7fdf372e-cf1b-47a2-bb4c-2d37f89c55ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>projectDescription</value>
      <webElementGuid>e3a18c3d-60b1-407e-998f-68cbf86cfa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>projectDescription</value>
      <webElementGuid>c06a8d24-114e-40f5-b111-2361d85c2e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c7e047e4-11d7-4d3d-adf2-90710a96eca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>5832c242-c502-4109-900a-6f54e91e4617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>9438927c-2566-4804-a601-6724c66b0ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;projectDescription&quot;)</value>
      <webElementGuid>28764b7a-58f6-4b9a-8131-bea18a81347c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='projectDescription']</value>
      <webElementGuid>bf320c78-de55-4843-9fe9-73e7c14e9608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/fieldset/div[3]/div/textarea</value>
      <webElementGuid>958dfbfa-6bab-41ea-a13f-6b4189e80291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a1d6bc65-2a49-49f9-94bf-d6979809ed33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'projectDescription' and @id = 'projectDescription']</value>
      <webElementGuid>610e3385-3135-498b-b617-01ed6421d45a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
