<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__establishmentDate</name>
   <tag></tag>
   <elementGuidId>112901db-b797-4731-9850-1a2c188c896f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#establishmentDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='establishmentDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0bf6d3f-f6e2-4a47-a48c-045bad764221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>establishmentDate</value>
      <webElementGuid>92ed2dd8-15a7-4282-85ab-f4ce194042fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>establishmentDate</value>
      <webElementGuid>ddc8a24c-c79a-4bf3-a690-313fe3e75e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>establishmentDate</value>
      <webElementGuid>ca629e52-3bf6-4da3-b0ee-9bf8961a56f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e5a9577f-54f4-4b3d-abfd-846881d48a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;establishmentDate&quot;)</value>
      <webElementGuid>9eae680a-e19f-4dee-a958-f3b029f12c01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='establishmentDate']</value>
      <webElementGuid>7f408f51-c062-4964-aed7-ea46234efd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[4]/div[2]/div/div</value>
      <webElementGuid>8be21a7a-0130-4479-a6b0-c843d5800c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div</value>
      <webElementGuid>cf5a050f-4d60-4345-b2c0-86ebeaa1e319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'establishmentDate']</value>
      <webElementGuid>1f5b5beb-cc80-40a6-8877-53acff01e456</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
