<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__englishName</name>
   <tag></tag>
   <elementGuidId>f914eb34-ffb8-48a4-b3c1-583d6fdeb5ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='englishName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#englishName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d8448a1-4a7b-4fc4-ab8b-4d8dc06d9d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>c6256309-27f8-4cf7-9a28-3877ed870678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>b0136229-2d55-42f4-8760-fd943e2b1677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>b5846cf6-4e67-48ad-ae54-b918c5580be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>2dc4c1ef-04d4-4135-a325-de891015c5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;englishName&quot;)</value>
      <webElementGuid>f19dfd8c-a2f9-473b-8254-adafecb0f7da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='englishName']</value>
      <webElementGuid>5a031c24-c334-49d0-aef2-0cc3ff837c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/management-council/div/div/div[2]/input</value>
      <webElementGuid>ed08088f-de60-4b2c-84a6-160e286a5180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//management-council/div/div/div[2]/input</value>
      <webElementGuid>3d1148b0-0e21-4b76-9914-f3d35eb9365f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'englishName']</value>
      <webElementGuid>1c2c2c40-08a4-4523-92d3-6a33ba2136ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
