<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jobTitle</name>
   <tag></tag>
   <elementGuidId>feaaa63c-ae0a-4ada-8c69-3157d2dffe71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#jobTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78729df6-9b2b-4f99-a9e2-1159dcd03b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobTitle</value>
      <webElementGuid>75c63edf-15eb-4d77-b65e-be5986fe1c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>jobTitle</value>
      <webElementGuid>28a5c034-a133-44e1-bb62-3ac103f85be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>jobTitle</value>
      <webElementGuid>c2a5f458-d582-4168-b6c1-592ea071e422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>4703f5bb-b49b-43f8-8f48-8ed7c5f117a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitle&quot;)</value>
      <webElementGuid>15386c28-9c99-4c3d-b8fd-f6b30099680c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobTitle']</value>
      <webElementGuid>1819cba9-4dcd-4b0d-bf1c-1ad9cbc788da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/management-council/div/div[2]/div[3]/input</value>
      <webElementGuid>4d3b63b2-8ba7-4586-8209-0310a7cc90e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//management-council/div/div[2]/div[3]/input</value>
      <webElementGuid>5b4230c7-c54e-44f6-a27f-018e40aa232d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jobTitle']</value>
      <webElementGuid>7c1a1d1a-dcbe-46e3-ad13-be36af11d543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
