<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__passportNumber (1)</name>
   <tag></tag>
   <elementGuidId>72d900d0-d33f-493c-83f8-2687cb81244e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passportNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#passportNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2299c7d-58b7-495a-9986-20f58f37775f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>abe33647-df90-4035-9705-97115ca55673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>c75597d8-3761-4fac-954d-df47850684b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>87c78274-78c8-476b-8e66-dd8846db7528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>229096f7-778b-49a8-91b9-2469c9a38153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passportNumber&quot;)</value>
      <webElementGuid>429715f1-4b4a-43f8-a018-7741cd310d1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passportNumber']</value>
      <webElementGuid>927ae9a0-9f3d-46d1-be9e-b1fd7ac226fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[6]/div/contact-officer/div/div[2]/div[2]/input</value>
      <webElementGuid>99d48082-9cb8-418c-9482-d2f49a92f11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//contact-officer/div/div[2]/div[2]/input</value>
      <webElementGuid>7ec8fe98-2bc6-47e4-8c30-e5c302db37ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'passportNumber']</value>
      <webElementGuid>d410d2c7-8aec-4099-bf7f-b163d3386b7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
