<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__englishName (1)</name>
   <tag></tag>
   <elementGuidId>28d614c8-145d-4e85-87ac-c6ac0ca70636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='englishName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#englishName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a62b457f-f5e0-439f-a92f-bc660c13546a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>07f8e947-2bf4-41e0-af53-e8c087cf1c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>767d65b9-2748-42ae-8b87-2fafba25c5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>d008900c-55ca-452c-bec5-4992ff09c4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>029ade1f-707e-4902-9729-8ace516933dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b79ce131-0150-433a-a329-b11e464daa21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;englishName&quot;)</value>
      <webElementGuid>60475d50-18a8-4854-9d97-a9f3bfc906db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='englishName']</value>
      <webElementGuid>8212c417-85b3-47d9-95e2-a0dc5d3978a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[6]/div/contact-officer/div/div/div[2]/input</value>
      <webElementGuid>13033a78-7018-4710-ac7c-1b2791d5b266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//contact-officer/div/div/div[2]/input</value>
      <webElementGuid>383b3b55-06a1-490e-9af0-cbf8f03f2fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'englishName']</value>
      <webElementGuid>e9ae51a0-1ec0-4649-9e8c-49d602f37ecc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
