<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__swiftCode</name>
   <tag></tag>
   <elementGuidId>356aa980-e652-400e-977a-5cd7cca8b98e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='swiftCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swiftCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67639294-1510-4eb9-9076-8af67a5ced3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swiftCode</value>
      <webElementGuid>143f54f1-2a69-442e-a921-ca97dae5f25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>swiftCode</value>
      <webElementGuid>932c9608-fe5b-4e2b-aaec-fcb7c7229e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>swiftCode</value>
      <webElementGuid>89c61670-b6bb-4b7f-a523-1531562b43b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>f41e61a3-6b1f-4010-93a5-9253cc6c57a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiftCode&quot;)</value>
      <webElementGuid>007422e7-7111-4f1c-8d16-bbc2296ef43d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='swiftCode']</value>
      <webElementGuid>c57759b0-5b1b-4396-b8d6-6a763c995c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/bank-account/div/div[2]/div/input</value>
      <webElementGuid>1ac72c2e-3712-4639-b769-f62d6cff7195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bank-account/div/div[2]/div/input</value>
      <webElementGuid>5a0db217-0a60-46a1-ad4b-07c94cee17f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'swiftCode']</value>
      <webElementGuid>072e7de6-7493-429f-ac7b-9b1bab99a04a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
