<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__arName</name>
   <tag></tag>
   <elementGuidId>7b30e40f-86e0-464b-b170-c63d34c3efd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#arName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='arName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b68040b-6aea-4b47-901d-909335567569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>arName</value>
      <webElementGuid>d4ae8c75-3695-4b5a-908c-f3b7cce1ed95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>401d72f0-59ef-4e11-821c-9b2341751338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>arName</value>
      <webElementGuid>371ed7f6-8402-4b09-add2-3be72057069e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arName</value>
      <webElementGuid>9f164cf9-68c8-4d40-bc3e-1306201f3a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched is-invalid</value>
      <webElementGuid>d63816f6-64c2-4a21-b1a7-8cd616e09a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arName&quot;)</value>
      <webElementGuid>af7852d6-7392-46a5-ac3d-6788e07fcd0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='arName']</value>
      <webElementGuid>0933bf50-def7-474e-8859-9687fa636630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/div[2]/input</value>
      <webElementGuid>bc474ca2-9e1d-4487-815d-a56e7e77b572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab/div/div[2]/div[2]/input</value>
      <webElementGuid>b3e7c84e-a16f-4756-813d-1d19a0fb3c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'arName']</value>
      <webElementGuid>7732c658-06d6-460d-8308-5847a5724266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
