<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fax</name>
   <tag></tag>
   <elementGuidId>017e06d9-65b3-42ef-9db9-a6b4c64493fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fax</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fax']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca69e264-2c97-4a17-94d5-1362cfb67b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>fax</value>
      <webElementGuid>009b11c7-1f52-475c-8491-c985947e9f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>276dbe08-da23-4f0a-b2e4-f93b8ee70d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>fax</value>
      <webElementGuid>0653900a-c3e0-49f3-85b9-22285473c1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fax</value>
      <webElementGuid>49f17cfd-3e79-4b93-9b84-584ed31ffb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>12ee75f3-46ff-4d59-9641-3a4f56cb95cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fax&quot;)</value>
      <webElementGuid>5a008da2-7537-4d72-9f22-9fe51506e4f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fax']</value>
      <webElementGuid>ebfaedc8-ac92-4dde-9de6-513f982c1aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[5]/div[2]/input</value>
      <webElementGuid>91636be7-6de5-429d-9e56-77640e4d6366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>8f8bdd4d-0ef3-4f20-8358-536584aac539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fax']</value>
      <webElementGuid>c824a5de-d657-4e54-ab1a-541021e4f977</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
