<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__passportNumber</name>
   <tag></tag>
   <elementGuidId>47a39c47-95a3-4eed-9fcd-e50d3211c3be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passportNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#passportNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d953c449-ea1d-4de2-8849-9020222de09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>349b5d63-5bc1-4257-a1e2-752c1988fa21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>1c9eb79d-c392-478a-a8f9-cb26b95ab3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>passportNumber</value>
      <webElementGuid>8c9783be-038b-46de-b761-c6ca6a5bec6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b87d2ea9-dcc2-489a-9b6f-b7536a11ec3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passportNumber&quot;)</value>
      <webElementGuid>46bfb8cd-e70e-47ee-b792-8dedf0a91707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passportNumber']</value>
      <webElementGuid>4f028960-2829-4d63-9391-c1cbc0d7935b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/management-council/div/div[3]/div/input</value>
      <webElementGuid>7f5c28d5-f944-4d74-888f-adf7e9c33c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//management-council/div/div[3]/div/input</value>
      <webElementGuid>27a7f7d3-0911-4b8e-9ae7-086c1e8d1128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'passportNumber']</value>
      <webElementGuid>42edbc94-d64b-4897-9b82-3e35e57f20aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
