<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phone (2)</name>
   <tag></tag>
   <elementGuidId>fc761755-3094-4607-827e-59cecfcdd232</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='phone'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-untouched.ng-pristine.ng-invalid.ng-star-inserted > div.row > div.col-sm-12.col-md-4.mb-4.position-relative > #phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ffb384f3-581a-468a-931f-4c596f77d8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>99507858-d394-4e8d-a80c-0c5f480bb780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebd04b69-21ef-4f52-9d0c-dc33dc561742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>7a95056a-b3dd-423b-9439-4705415ab018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>e99c4c99-401b-4a90-9a00-650b51e34e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>78a36bb0-cdd7-4c9b-a7c6-50e0e5355d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c34-105 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c34-105 ng-star-inserted&quot;]/contact-officer[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4 mb-4 position-relative&quot;]/input[@id=&quot;phone&quot;]</value>
      <webElementGuid>b90d1529-80ae-4032-a1b7-8cecefb39f0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='phone'])[2]</value>
      <webElementGuid>cb98e887-3afb-4508-8e2e-079faf331bdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[6]/div/contact-officer/div/div/div[3]/input</value>
      <webElementGuid>b4f43520-cfe6-49d0-ba16-3a194ccb39dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//contact-officer/div/div/div[3]/input</value>
      <webElementGuid>a57ee12c-0815-4423-94c6-702bb2dbb8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'phone']</value>
      <webElementGuid>593f0b2e-1e9b-45ce-a937-dda6adacb8ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
