<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__firstSocialMedia</name>
   <tag></tag>
   <elementGuidId>81e0b432-2c49-425c-909b-b19f5ab1a70d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#firstSocialMedia</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='firstSocialMedia']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a702178-a144-4141-b760-6717a45511b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>firstSocialMedia</value>
      <webElementGuid>268aab67-0937-4232-9978-7dec12adec9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae603280-13df-4728-9857-d49ff495fc12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>firstSocialMedia</value>
      <webElementGuid>84b7b78b-35c0-44a2-9ac7-e41e7931bbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>firstSocialMedia</value>
      <webElementGuid>b12f19f6-461b-4c4b-bd7a-0d4f67b4bbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>54d20152-8243-4f9f-aec3-060516cfdbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;firstSocialMedia&quot;)</value>
      <webElementGuid>86dd2d40-8ed8-4cea-9e49-4be9de4e63d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='firstSocialMedia']</value>
      <webElementGuid>077dae77-798e-4323-a4f7-e55a4e0b8ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[7]/div/input</value>
      <webElementGuid>9b761957-b2ae-4647-a6b5-ed86aa80f88b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>e9545c2e-03d7-4d20-b55f-99f232fc3aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'firstSocialMedia']</value>
      <webElementGuid>9cd1358a-3799-45c3-8aec-921128dbf8cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
