<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__oldLicenseFullSerial (1)</name>
   <tag></tag>
   <elementGuidId>87334237-fb7b-45b3-9779-88d319b80ed6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='oldLicenseFullSerial']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oldLicenseFullSerial</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2275c037-b431-48c7-8b21-ee66fd040668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>d9f8ed01-7853-48e2-8b84-5e16340e44a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51190dd8-662c-4612-a377-fc03758b675f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>f14b220b-b1a2-486d-b8fd-c27fb11b54c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oldLicenseFullSerial</value>
      <webElementGuid>a7c77c23-de55-43c2-8b7a-bf98ea02ad3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>41f468e8-9015-4f28-82ef-164214c2f65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oldLicenseFullSerial&quot;)</value>
      <webElementGuid>ecde1296-9d63-4bf3-9345-05d66d38af24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='oldLicenseFullSerial']</value>
      <webElementGuid>73b1e8c6-b7bd-44d3-84c8-5ad958a6afbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div/div[2]/div/input</value>
      <webElementGuid>5f0e3bc1-f4b9-40ee-80a3-74ff0f6964dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tab/div/div/div[2]/div/input</value>
      <webElementGuid>f2e4eda5-56ad-4376-9a32-c4e67c0efd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'oldLicenseFullSerial']</value>
      <webElementGuid>22667528-6449-4e71-a3c1-0bbba5295d27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
