<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__partnerName</name>
   <tag></tag>
   <elementGuidId>ec5c94c9-47da-4ea4-8035-351bb0f26013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='partnerName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#partnerName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c74d13c-dc8c-4ad1-a1c4-3be07c79c2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partnerName</value>
      <webElementGuid>5dd4df9b-c3e7-48c8-b7ab-3d56243f106f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>partnerName</value>
      <webElementGuid>3bc2ad74-3d54-4502-abb2-bd588a72bacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>partnerName</value>
      <webElementGuid>79698270-ca9d-4f5d-85c9-e971c3705444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>5efc7302-1ec8-4bbb-9dd2-b9c30a76fd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partnerName&quot;)</value>
      <webElementGuid>b95bf177-3a9c-41e7-8c52-9c8aec4f9229</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partnerName']</value>
      <webElementGuid>2b7196b6-d8d8-46a9-8300-1936a7c79cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/bank-account/div/div[3]/div/input</value>
      <webElementGuid>4063ec8d-e2a2-4de0-9826-0170337a0bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bank-account/div/div[3]/div/input</value>
      <webElementGuid>87f3f5a8-0cbb-4255-9e37-935dfb8d5161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'partnerName']</value>
      <webElementGuid>19676a01-ce73-488c-9c91-898cba9ba836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
