<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phone (1)</name>
   <tag></tag>
   <elementGuidId>d9cc501d-80f7-4b43-a926-b6c5c8971d77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='phone'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-untouched.ng-pristine.ng-invalid.ng-star-inserted > div.row > div.col-sm-12.col-md-4.mb-4.position-relative > #phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b5314ee-e4df-4c59-8237-013afa85e052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>602f7645-0731-4cba-996f-568225c48582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>ebd855e7-b56b-400b-aa66-cbc06b499947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>0adf450b-333f-45d0-a347-446f57816cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b6d0c8df-4c0c-4215-adc0-bb1943338f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c34-103 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c34-103 ng-star-inserted&quot;]/management-council[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4 mb-4 position-relative&quot;]/input[@id=&quot;phone&quot;]</value>
      <webElementGuid>8b91c788-69a9-4434-a86e-681537e8a441</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='phone'])[2]</value>
      <webElementGuid>01384090-f44d-4ec6-a273-8cadbf8e71a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[4]/div/management-council/div/div/div[3]/input</value>
      <webElementGuid>e138712a-37b4-4e91-8104-68de6ebc9796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//management-council/div/div/div[3]/input</value>
      <webElementGuid>5e59afb2-4233-4ed4-8f1e-b9e52ffa8f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phone']</value>
      <webElementGuid>7c12d691-e2c8-49cd-8030-48e79683b89b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
