<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__targetedGroup</name>
   <tag></tag>
   <elementGuidId>57edb314-e329-41e0-8284-4f77fefdb7d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='targetedGroup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#targetedGroup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ddc9f6b1-d94c-4328-bb99-35c7b10ecd02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>targetedGroup</value>
      <webElementGuid>9d019cbe-f4d8-49f4-b385-631b1c434100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ae39515-9267-4cf8-a3f7-4d3c2ad2acb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>targetedGroup</value>
      <webElementGuid>cdea0d25-7711-42e2-b0cb-a236ce1dd62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>targetedGroup</value>
      <webElementGuid>dd382292-ea2f-4e42-9a6e-612f94e146f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched is-invalid</value>
      <webElementGuid>053a231a-6a7e-481d-9ba6-703d2cf65987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;targetedGroup&quot;)</value>
      <webElementGuid>6f616ac2-e1ef-405e-b210-9ce0a6928b1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='targetedGroup']</value>
      <webElementGuid>9de939ae-d6ef-49ff-a3e1-aa3389e4ae21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/target-group/div/div/div[2]/textarea</value>
      <webElementGuid>3135b694-31bf-4d17-aef9-ab683cb828a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>51282862-0c5f-4324-b54f-bc56b5cb49a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'targetedGroup']</value>
      <webElementGuid>77bd035b-59f6-486f-b0a2-5033e1f3674c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
