<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__locationMap</name>
   <tag></tag>
   <elementGuidId>22d0d1e4-9a98-41d6-a458-59112800fefd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.input-group-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95665f51-fa4d-490a-89c5-dc4714e96a75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4caa247c-ae30-4e13-a58b-ef01d57cee12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-text</value>
      <webElementGuid>249543f3-695e-4ca6-81a3-3fc637ba7c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c135-84 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c135-84 ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/collection-item[1]/form[@class=&quot;ng-star-inserted ng-touched ng-dirty ng-valid ng-submitted&quot;]/fieldset[@class=&quot;border border-1 rounded-1 p-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 mb-4 position-relative&quot;]/div[@class=&quot;input-group&quot;]/button[@class=&quot;input-group-text&quot;]</value>
      <webElementGuid>4968ffa9-200a-4854-96a8-4e655e643394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>3e4b2f81-2464-40b9-825d-103513244935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collection-item/form/fieldset/div[2]/div/div/div[2]/div/button</value>
      <webElementGuid>64183328-e8d8-4336-8d8f-53dd04428c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::button[1]</value>
      <webElementGuid>4118504e-a95b-494b-839e-262195e6e349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::button[1]</value>
      <webElementGuid>e18ff890-1e88-4a4a-a6d2-e0b93a0d9caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/button</value>
      <webElementGuid>643d3614-62f1-434b-b43d-98540a38127d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>4334dc98-60f7-4a03-847b-9f5d8f189ec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
