<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CloseAttachmentsPage</name>
   <tag></tag>
   <elementGuidId>8815f466-36e9-4556-9687-6155c14bc9a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='من'])[2]/following::button[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dialog-actions > button.btn.btn-secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6b75822e-e265-4a79-939a-10c17853677f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary</value>
      <webElementGuid>0503e4a1-438f-4563-aec5-1ee9e3580b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>أغلق</value>
      <webElementGuid>8bed41a4-51b9-4cb9-9756-07023fdee8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-2&quot;)/app-dialog-container[@class=&quot;ng-tns-c40-49 ng-trigger ng-trigger-dialogContainer ng-star-inserted rounded shadow&quot;]/custom-attachment-popup[@class=&quot;dialog-item ng-star-inserted&quot;]/div[@class=&quot;dialog-actions&quot;]/button[@class=&quot;btn btn-secondary&quot;]</value>
      <webElementGuid>186268d1-feb1-40a8-b3b3-85d1c806294f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/app-dialog-container/custom-attachment-popup/div[3]/button</value>
      <webElementGuid>ebccab8c-71bc-44e4-b893-d234abee393b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='من'])[2]/following::button[1]</value>
      <webElementGuid>2cbc3211-c783-4930-9ec1-5d0bc5321e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[2]/following::button[1]</value>
      <webElementGuid>76d1d198-2c6f-4440-be09-7ea79a27523a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='أغلق']/parent::*</value>
      <webElementGuid>fb3650f2-015b-470f-9ec3-697ef078b2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>bd93b429-66f0-455c-a602-891e13d3c598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'أغلق' or . = 'أغلق')]</value>
      <webElementGuid>5bf05f79-4b8c-4beb-8310-cdd959ba456f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
