<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_addNewCollectionService(plus button)</name>
   <tag></tag>
   <elementGuidId>15c6a5a8-9bc5-478a-a5ae-fb3c7fcafe9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collection-item/app-page-header/div/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-plus-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ccf67b14-f721-4f30-ba0c-e356a2b3b047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-plus-box</value>
      <webElementGuid>a5f1faf3-6243-4a66-90e5-1c120e6fe4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c135-84 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c135-84 ng-star-inserted&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/collection-item[1]/app-page-header[@class=&quot;col-md-6 col-sm-12 ng-star-inserted&quot;]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;align-items-center&quot;]/button[@class=&quot;btn btn-link outline-none ng-star-inserted&quot;]/i[@class=&quot;mdi mdi-plus-box&quot;]</value>
      <webElementGuid>eb6b5c9e-076f-4091-9e2e-faa099333e75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collection-item/app-page-header/div/div/button/i</value>
      <webElementGuid>86cb5847-6b57-4806-b083-f82942860bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-page-header/div/div/button/i</value>
      <webElementGuid>d8c0f657-1a8e-4a49-9ce2-9255abddee4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
