<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__plateUnit</name>
   <tag></tag>
   <elementGuidId>91f99801-43a1-4281-b18b-52156d6d08f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plateUnit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#plateUnit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4c11b82-4df5-46ed-b1d6-0400745d9b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42f4db48-0b2d-4fb6-bc9f-54fb97f0ead4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plateUnit</value>
      <webElementGuid>4c92909e-84c9-449c-8dec-9151c3105172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>unit</value>
      <webElementGuid>d25807bf-ad46-4799-ae66-a5b690f399fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>unit</value>
      <webElementGuid>c3f84a99-76e1-434f-978e-5a49cbee54ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fw-bold fs-3 ng-pristine ng-invalid ng-touched is-invalid</value>
      <webElementGuid>a6b3d058-527e-4335-9e0d-5bb2696f7080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plateUnit&quot;)</value>
      <webElementGuid>9da23530-d88a-4e4e-b151-c9011556c7bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plateUnit']</value>
      <webElementGuid>938a6a31-61e5-4f04-a201-ea380c1c662b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collection-item/form/fieldset/div[2]/div[2]/building-plate/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>3c09a9b9-b5e6-46a1-8bf4-8709cb31ae8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/input</value>
      <webElementGuid>3166db63-df2b-4210-a7b3-8106ee6e4bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'plateUnit']</value>
      <webElementGuid>e8148ead-d2c4-4a26-b011-4b96722792a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
