<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__plateStreet</name>
   <tag></tag>
   <elementGuidId>35669170-2ef3-4b9c-84d2-1bf2a7b1f024</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plateStreet']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#plateStreet</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>364dba3a-40eb-4248-84e0-eebe7ca3a7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7998db0e-94c6-4d5b-876d-f927def6fd4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plateStreet</value>
      <webElementGuid>906f54a7-779f-40d9-93b2-fe1c0b92e551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>street</value>
      <webElementGuid>15bd3136-35bb-47a7-bbd3-6c67dc0a74ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>street</value>
      <webElementGuid>20c18bd4-d8a3-466c-9c6c-2b1ca495193b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fw-bold fs-3 ng-pristine ng-invalid ng-touched is-invalid</value>
      <webElementGuid>420e250e-03ed-41e9-8e5a-9f2074e6eb55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plateStreet&quot;)</value>
      <webElementGuid>d67be809-8278-4da4-9312-df690cb406fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plateStreet']</value>
      <webElementGuid>ff689e3e-5f2a-4d0d-bb8c-fde1fb430c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collection-item/form/fieldset/div[2]/div[2]/building-plate/div/div[2]/div[2]/input</value>
      <webElementGuid>f5181d34-181c-48bd-9697-242bc7593e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//building-plate/div/div[2]/div[2]/input</value>
      <webElementGuid>8c5a2aff-bc55-4d4e-8b71-45e817c6aed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'plateStreet']</value>
      <webElementGuid>fbd405c5-a0d2-46eb-ae48-dc15d44d54f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
