<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_file</name>
   <tag></tag>
   <elementGuidId>6b2595a9-873e-42f6-bc29-942a2782de45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dialog-content > div > input[type=&quot;file&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='file'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>676ebc67-33b7-4ab4-9a1f-29e68b3684d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>0ef86819-94f9-475e-94ab-ff8bf512ca51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf,.jpeg,.png,.docx,.jpg</value>
      <webElementGuid>cd156e62-5df3-48ce-b054-c80bbe75637e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-2&quot;)/app-dialog-container[@class=&quot;ng-tns-c3-143 ng-trigger ng-trigger-dialogContainer ng-star-inserted rounded shadow&quot;]/custom-attachment-popup[@class=&quot;dialog-item ng-star-inserted&quot;]/div[@class=&quot;dialog-content&quot;]/div[1]/input[1]</value>
      <webElementGuid>9797d684-5241-4d33-9979-bbc91628399f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='file'])[2]</value>
      <webElementGuid>4a3e1ff1-f49d-47d6-96b0-a502735985c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-2']/app-dialog-container/custom-attachment-popup/div[2]/div/input</value>
      <webElementGuid>76fe5a58-acc4-4652-8ca1-be3aec880fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//custom-attachment-popup/div[2]/div/input</value>
      <webElementGuid>4e6c0461-a759-4949-a7b7-ac1cd945e98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file']</value>
      <webElementGuid>05f1a57c-dbb3-43e6-aabd-ae56c8c9eeac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
