<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__OldLicenseFullSerial</name>
   <tag></tag>
   <elementGuidId>c693ab78-b605-4922-9c56-f4db83ebbdae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchControl']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'searchControl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchControl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea63492c-b8cd-439d-a5fa-d4438561e0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchControl</value>
      <webElementGuid>839057d4-3ca3-4521-8d1a-71b8bebd06cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched is-invalid</value>
      <webElementGuid>0e2adcea-35fa-46d1-b97a-2ae8b6908242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchControl&quot;)</value>
      <webElementGuid>d1ac6c3d-7c38-4cd5-a957-83c0f2e7742f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchControl']</value>
      <webElementGuid>d8f6e19a-42fe-40b4-9568-cda75ce9cc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collection-item/form/fieldset/div/div/div/input</value>
      <webElementGuid>e4131034-f37e-4a32-bae5-9cd1126b090c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/input</value>
      <webElementGuid>a47d7150-2249-4fea-8555-487c881f93e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchControl']</value>
      <webElementGuid>e96d7eef-e9a0-4634-a2e0-5b88ede4b80f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
