<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__identificationNumber</name>
   <tag></tag>
   <elementGuidId>ee4058c3-96b8-4f21-a069-d1766d104f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identificationNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#identificationNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc1cca66-e525-48f7-9947-5218d6c1faaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>55293ce5-053d-47e5-b49c-8bd008c31577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>b94f2f33-cb1b-487c-a350-17c1cd7f9e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>identificationNumber</value>
      <webElementGuid>9f7bbaf8-aa8b-487a-b039-5ea2731f09ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched is-invalid</value>
      <webElementGuid>bc8b9a41-1ff1-482f-9422-c4e199d0d1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identificationNumber&quot;)</value>
      <webElementGuid>789db93c-bbf2-4cc2-b049-5a3bf74c7b52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identificationNumber']</value>
      <webElementGuid>67628534-575b-44c4-944d-d1df0da22d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collection-item/form/fieldset/div/div[3]/input</value>
      <webElementGuid>88a281ae-f24c-4500-a5d6-193238a1cf5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[3]/input</value>
      <webElementGuid>ab5236d5-ccb5-407e-af9a-006cfbac00e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'identificationNumber']</value>
      <webElementGuid>ba7303e8-baef-4e21-a3e3-71d8d45cc264</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
