<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__plateZone</name>
   <tag></tag>
   <elementGuidId>05ed0043-eb27-45a1-a791-2068821d15c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plateZone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#plateZone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae4f2c18-f628-42a4-bef5-db4b4d845ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0dd9456-b8ba-4fbf-916a-4c3ef365fb62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plateZone</value>
      <webElementGuid>c8146124-a762-48ce-ba3d-4666493470d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>zone</value>
      <webElementGuid>e4d13881-1f9d-49d9-8138-dbc26c5e4c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>zone</value>
      <webElementGuid>4352ba0e-52d2-421e-9027-911ca74ef434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fw-bold fs-3 ng-pristine ng-invalid ng-touched is-invalid</value>
      <webElementGuid>736bc4d1-0d6a-4493-ae12-6bb2c741789c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plateZone&quot;)</value>
      <webElementGuid>eae63c87-ff1a-45b2-8c81-2a8fcb59e996</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plateZone']</value>
      <webElementGuid>8ca6f264-4a03-4645-9ef6-beb417689936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collection-item/form/fieldset/div[2]/div[2]/building-plate/div/div/div[2]/input</value>
      <webElementGuid>d784fe46-db30-48f4-8ef7-576bf1910034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//building-plate/div/div/div[2]/input</value>
      <webElementGuid>c5a833e0-69be-4113-a391-c05da3607dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'plateZone']</value>
      <webElementGuid>825dc8ab-b6e4-4d6d-820d-b767ba3d8789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
