<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NA_attachmentUploader</name>
   <tag></tag>
   <elementGuidId>1238adbd-c2cd-4f42-973f-cd7cfec704a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attachmentUploader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attachmentUploader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9b49a49-1c91-40b3-b31c-73a8d809a161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>003a2ab1-15c3-41ab-b4ab-f250cc66c29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attachmentUploader</value>
      <webElementGuid>605e9872-2f27-4300-8533-2840b1732303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf</value>
      <webElementGuid>8463f19f-a2ff-40ba-a1bf-f62676d72576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attachmentUploader&quot;)</value>
      <webElementGuid>62501ed4-54ba-4ae2-a0c0-5319bd64ee63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attachmentUploader']</value>
      <webElementGuid>43baad7c-38cf-45e1-87dc-a38e4f1251bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/attachments/div/input</value>
      <webElementGuid>b675d0f1-0097-42c3-b155-52e13ccf6f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//attachments/div/input</value>
      <webElementGuid>6a9d4040-92ec-4333-a48f-d24fdc5954ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'attachmentUploader']</value>
      <webElementGuid>77392e33-a25f-4a2d-ad93-619db18518c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
