<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__plateBuildingNo</name>
   <tag></tag>
   <elementGuidId>f90bf88e-a262-465e-bebc-8d839eb1d218</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='plateBuildingNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#plateBuildingNo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d5de931-e879-4e1a-b7cf-a7b0e92d9e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12b0cfe3-bbd9-4396-9ee9-bc8584420a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plateBuildingNo</value>
      <webElementGuid>8aa8114a-7c84-4f3b-b04e-2bc1d9f0c753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>buildingNo</value>
      <webElementGuid>d66a8853-e9b2-4648-aa29-aeb4adaf377e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>buildingNo</value>
      <webElementGuid>b16b6af0-667d-4d62-a80e-3dfd2c0a96c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control fw-bold fs-3 ng-pristine ng-invalid ng-touched is-invalid</value>
      <webElementGuid>04a109e9-7297-41b8-b0c9-c91a618994d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plateBuildingNo&quot;)</value>
      <webElementGuid>f52d31dc-ed79-4c61-ab50-53b4df83e7df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='plateBuildingNo']</value>
      <webElementGuid>ee667549-7dd1-4a83-81bf-cbdf39783787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div[2]/collection-item/form/fieldset/div[2]/div[2]/building-plate/div[2]/div/div[2]/input</value>
      <webElementGuid>27da6ad2-afbc-4422-9201-c187082de4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>a0a1ab6b-7ca1-4154-a360-f2ecb5aee7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'plateBuildingNo']</value>
      <webElementGuid>0d4e88c8-bfa1-4616-9ff4-a9ef77ba0297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
