<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__Reload (Refresh)</name>
   <tag></tag>
   <elementGuidId>786143f3-bdf8-49e0-a948-fba4e1a2321c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/app-user-inbox/div/div/app-table/div/table/thead/tr/th/table-header/div/div/button/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//i[@class = 'mdi mdi-reload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.mdi.mdi-reload</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>4d23e672-af42-445a-abe4-3505921ba465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi mdi-reload</value>
      <webElementGuid>7f0161a3-27b4-4966-8eae-874e226f7d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;h-100 container-fluid p-3&quot;]/app-user-inbox[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/app-table[1]/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;cdk-table table border border-1 ng-star-inserted&quot;]/thead[1]/tr[@class=&quot;cdk-header-row ng-star-inserted&quot;]/th[@class=&quot;cdk-header-cell extra-header cdk-column-extra-header ng-star-inserted&quot;]/table-header[1]/div[@class=&quot;d-flex flex-row justify-content-start align-items-center bg-primary p-2 text-white&quot;]/div[1]/button[@class=&quot;btn icon-btn ng-star-inserted&quot;]/i[@class=&quot;mdi mdi-reload&quot;]</value>
      <webElementGuid>7206d3c5-181c-4c46-bb83-f6348cf98635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/app-user-inbox/div/div/app-table/div/table/thead/tr/th/table-header/div/div/button/i</value>
      <webElementGuid>dd935ecc-f352-4d0c-9c71-bd8cbd44be04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table-header/div/div/button/i</value>
      <webElementGuid>0f680a27-3372-4fdc-bff8-6b33b71a4563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
