<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon__Home (Arabic UI)</name>
   <tag></tag>
   <elementGuidId>1198a2e9-2a9c-49d8-99ea-15cbfa88bac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.mdi.custom-icon-size.mdi-home.ng-tns-c55-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-back-logout-items']/button[2]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e5e44cb5-9688-4bab-92d3-7fedbb175c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mdi custom-icon-size mdi-home ng-tns-c55-2</value>
      <webElementGuid>9263d19e-5ac2-43c7-a818-c8fd197d77c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-back-logout-items&quot;)/button[@class=&quot;icon-btn ng-tns-c55-2&quot;]/i[@class=&quot;mdi custom-icon-size mdi-home ng-tns-c55-2&quot;]</value>
      <webElementGuid>f13330de-54e2-4d62-9615-ff2380997ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-back-logout-items']/button[2]/i</value>
      <webElementGuid>5cfd7f0b-c8dd-4e32-a0cc-169264bb53ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/i</value>
      <webElementGuid>b64e38f1-a91c-47e3-a2a0-38d4801ab3d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
