<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_service (common)</name>
   <tag></tag>
   <elementGuidId>2f208765-5d52-48bc-8f08-2d5f7054d214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.flex-grow-1.sidebar-menu-item-text.text-truncate.ng-tns-c80-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu-item-list']/app-sidebar-menu-item-list/ul/li[5]/app-sidebar-menu-item-list/ul/li/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d9fbfb0d-1b01-493d-9470-5173dd0d60fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow-1 sidebar-menu-item-text text-truncate ng-tns-c80-14</value>
      <webElementGuid>0705a360-7b7d-440e-bd00-0da23a67268f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>الخدمة</value>
      <webElementGuid>eba12557-cc75-4064-bfcc-731bd3a10339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>الخدمة</value>
      <webElementGuid>7ebb9f85-a00b-414f-82ff-800b17f035aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-list&quot;)/app-sidebar-menu-item-list[@class=&quot;ng-tns-c81-2 ng-tns-c80-3 ng-star-inserted&quot;]/ul[@class=&quot;ng-tns-c80-3 level-1 sidebar-menu-list&quot;]/li[@class=&quot;sidebar-menu-item ng-tns-c80-3 parent-menu-item has-children ng-trigger ng-trigger-expendCollapse ng-star-inserted expanded&quot;]/app-sidebar-menu-item-list[@class=&quot;ng-tns-c80-14 ng-tns-c80-3 ng-star-inserted&quot;]/ul[@class=&quot;ng-tns-c80-14 level-2 sidebar-menu-list&quot;]/li[@class=&quot;sidebar-menu-item ng-tns-c80-14 px-2 ng-trigger ng-trigger-expendCollapse ng-star-inserted&quot;]/a[@class=&quot;d-flex flex-row align-items-center overflow-hidden position-relative ng-tns-c80-14 px-2 justify-content-start color:&quot;]/span[@class=&quot;flex-grow-1 sidebar-menu-item-text text-truncate ng-tns-c80-14&quot;]</value>
      <webElementGuid>d2b64529-8ea5-4c68-ace0-a7667f62591d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu-item-list']/app-sidebar-menu-item-list/ul/li[5]/app-sidebar-menu-item-list/ul/li/a[2]/span</value>
      <webElementGuid>1a1ebe1b-e31b-4a06-8abc-0a7228396b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='طلبات التوظيف'])[1]/following::span[1]</value>
      <webElementGuid>f7952e9b-3870-4278-80c5-f8576a4d71fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تقارير المساعدات الجزئية'])[1]/following::span[2]</value>
      <webElementGuid>8941f658-9fc6-4ef6-bb7e-6a7c37313020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='بحث'])[1]/preceding::span[1]</value>
      <webElementGuid>ad9a9961-82f6-4f4a-86df-633ddaae4244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='اقتراح نشاط توعوي'])[1]/preceding::span[2]</value>
      <webElementGuid>69e20c2e-a87c-43d4-bc96-3295ace3a5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='الخدمة']/parent::*</value>
      <webElementGuid>fdf65506-dfa4-4c0a-b89a-9b3834c860c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/app-sidebar-menu-item-list/ul/li/a[2]/span</value>
      <webElementGuid>6c77c43e-f88b-45b4-bcc6-7885ff5194cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'الخدمة' and (text() = 'الخدمة' or . = 'الخدمة')]</value>
      <webElementGuid>b6e7dac4-698f-40bc-a615-35f1b4892c4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
