<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__establishmentDate</name>
   <tag></tag>
   <elementGuidId>4f6de625-7b85-44d7-bda2-1ca91745fd5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='establishmentDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#establishmentDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc741d76-3467-4ba6-9c89-cc637bab9eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>establishmentDate</value>
      <webElementGuid>117869cd-bfc5-41d9-bdc8-474660d19938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>establishmentDate</value>
      <webElementGuid>6d50e408-a235-411f-bc18-c11d91e94213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>establishmentDate</value>
      <webElementGuid>1da841ca-a39f-47e5-be1c-fb0b27740c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c9958d72-34d8-45eb-a63e-35a783c02679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;establishmentDate&quot;)</value>
      <webElementGuid>fd0eb106-4b2c-464d-8700-4b3ea9f08537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='establishmentDate']</value>
      <webElementGuid>ff2cd82b-dd3c-4d11-a8ec-4df7ef9b0fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div/div[2]/div[3]/div/div</value>
      <webElementGuid>4bf27cf3-0da2-48ee-899a-07544d404c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div</value>
      <webElementGuid>081d83a4-7564-4efe-a0e6-671b6ecf9355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'establishmentDate']</value>
      <webElementGuid>6c308059-48b6-475a-9ddd-793db7d605f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
