<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__licenseDuration</name>
   <tag></tag>
   <elementGuidId>d96e2fb1-208a-4553-8634-e80e3ac7ab44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='licenseDuration']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#licenseDuration</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1489823a-a9ad-4af2-8e11-0586443a07f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>licenseDuration</value>
      <webElementGuid>7139f320-5f39-44f9-8582-2c316db3dd4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4511c65b-9ff9-4c67-bc3a-453f46416571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licenseDuration</value>
      <webElementGuid>fa287d6d-55ff-40dd-a4fb-5b02ab527bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5772b70-2f82-4a7a-9eef-50980b98a22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>87c0100c-2a6f-4079-815a-3eeac52496c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;licenseDuration&quot;)</value>
      <webElementGuid>1a54f17e-6c26-44bb-8138-9661ab5f1e76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='licenseDuration']</value>
      <webElementGuid>a59cf4cc-bf3c-4a93-9af1-95f70b5e9c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab/div/div/div[3]/div[3]/div/div/input</value>
      <webElementGuid>d129f8f5-5bdd-4e99-8c9d-d3a33a70a1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/input</value>
      <webElementGuid>86ab058e-b2f7-4ced-afe2-27f419e8bad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'licenseDuration' and @type = 'text']</value>
      <webElementGuid>37da60c8-5461-4f41-bb29-88c47ca6691e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
