<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__headQuarterType</name>
   <tag></tag>
   <elementGuidId>0f981a6b-185b-44e8-a6cb-3227bba3cb59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headQuarterType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-input > #headQuarterType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5301b48d-646b-4183-9a13-595194e6df0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>7bd0f7da-c85f-417a-90dd-05ea047a8887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1aec56ec-726c-4ac7-be54-66da4be52f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fe96296c-8f17-4828-a872-9f2da235b880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>84ce37a9-3ec3-45c8-9805-a48ca2198a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9aac38c-4e58-4166-859c-a6bd199170c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headQuarterType</value>
      <webElementGuid>a40fdb50-2850-4ff6-9892-9866a9e7d755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c34-293 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c34-293 ng-star-inserted&quot;]/div[@class=&quot;ng-invalid ng-star-inserted ng-untouched ng-pristine&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4&quot;]/div[@class=&quot;d-flex align-items-center justify-content-start gap-2&quot;]/div[@class=&quot;mb-4 ng-select-wrapper flex-grow-1&quot;]/ng-select[@id=&quot;headQuarterType&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[@id=&quot;headQuarterType&quot;]</value>
      <webElementGuid>56744af0-f7ad-4133-85c0-ef90cd285200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headQuarterType']</value>
      <webElementGuid>0ac466dc-543f-4af0-b438-ee8cdfbf5db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='headQuarterType']/div/div/div[2]/input</value>
      <webElementGuid>e65fc1f4-ddba-42f9-b8ce-5a6114281c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/ng-select/div/div/div[2]/input</value>
      <webElementGuid>1c12ffff-634f-4f34-b589-3ebe68fa1d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'headQuarterType']</value>
      <webElementGuid>833478e6-5ef2-44b0-8378-e6bd176675f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
