<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__phone</name>
   <tag></tag>
   <elementGuidId>af4c4a62-ea26-4c85-a686-2b41476f87c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='phone'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>executive-management.ng-star-inserted > div.ng-untouched.ng-pristine.ng-invalid.ng-star-inserted > div.row > div.col-sm-12.col-md-4.mb-4.position-relative > #phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73d1b3f5-fa70-45ee-bd56-0c8d9a0a145a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>224e22d8-02da-4e0e-8d90-c5300f582e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>238ad26b-939a-4a94-9776-5625778ca6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>f28cb8cd-bc78-4ab6-898a-912ff5ce22ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9de28008-3661-40da-848a-531e71a2d208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c34-103 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c34-103 ng-star-inserted&quot;]/executive-management[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;ng-untouched ng-pristine ng-invalid ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4 mb-4 position-relative&quot;]/input[@id=&quot;phone&quot;]</value>
      <webElementGuid>a7ea3033-72fa-444b-9297-43036fccd71a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='phone'])[2]</value>
      <webElementGuid>07cf9e70-f4ec-4a9b-bc03-c535334d4c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/executive-management/div/div/div[3]/input</value>
      <webElementGuid>1acae7d4-9112-4419-bb97-dc46ba8a8c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//executive-management/div/div/div[3]/input</value>
      <webElementGuid>6e2afc55-f533-4a3a-b6d8-3177eb368308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phone']</value>
      <webElementGuid>3e2a66ad-204a-4ca8-8179-e4aa7e6e32e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
