<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__swiftCode</name>
   <tag></tag>
   <elementGuidId>166bd756-fbf0-4b86-a2cd-20c05c35877f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='swiftCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swiftCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d75c030-87d2-4913-b532-04dfae04eff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swiftCode</value>
      <webElementGuid>980fd51c-e2e7-4357-ac51-1b61b40aaf97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>swiftCode</value>
      <webElementGuid>1db619ef-c138-4c10-82db-b0f057b19ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>swiftCode</value>
      <webElementGuid>97ff3679-a7ce-4996-bb24-2f56a451817e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>281a8ea0-ba67-4121-8dfb-66ed3d19fd51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiftCode&quot;)</value>
      <webElementGuid>7232e263-a253-4f4a-80ac-e8475592bd8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='swiftCode']</value>
      <webElementGuid>ebcc7bac-1cc4-46b8-8a47-4f6321f10884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/bank-account/div/div[2]/div/input</value>
      <webElementGuid>bdde0999-6b3d-4f3c-b512-80064c9192d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bank-account/div/div[2]/div/input</value>
      <webElementGuid>d20326c3-ee88-4b7c-b336-7404393bfab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'swiftCode']</value>
      <webElementGuid>34b82a5f-8d10-422f-b79e-e4da408ff298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
