<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__englishName</name>
   <tag></tag>
   <elementGuidId>a0902db4-6a1e-46d7-b7f4-98c0442fe72b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='englishName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#englishName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8e7a478c-cf61-464c-9c1d-ba7ab7c017fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>b2efe904-81dd-45a0-a143-e1c46178d724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>e5e3b4ce-0e69-4fc3-9db3-522ff8e10ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>englishName</value>
      <webElementGuid>04525414-4323-47c6-9186-56bc413827be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>1a4e0942-7e95-4278-81b9-6e040e217780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;englishName&quot;)</value>
      <webElementGuid>d28e93ff-906d-45cd-9ce8-e58f2f6a3210</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='englishName']</value>
      <webElementGuid>08ebe3dd-5aac-4e2d-8a94-6667164e61b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/executive-management/div/div/div[2]/input</value>
      <webElementGuid>898248b8-58bd-480e-b893-1cb1d53596b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//executive-management/div/div/div[2]/input</value>
      <webElementGuid>f91258d8-a7e7-4ba5-bf43-14e6fb29ffff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'englishName']</value>
      <webElementGuid>63971817-c792-49ff-b5c3-d4387be2d1a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
