<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bankName</name>
   <tag></tag>
   <elementGuidId>0c695923-7759-47b5-b9be-817e0e132a1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bankName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bankName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98504d2a-7b3d-4bd5-9f06-d1375e74b26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bankName</value>
      <webElementGuid>c9dfd19c-b851-466d-87a6-5043fc2bc62a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>bankName</value>
      <webElementGuid>ad2b8eee-7e5c-474a-9c91-f8d7cc3abbf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>bankName</value>
      <webElementGuid>7de75981-ae32-44f2-9660-a288241bef9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>ac2a3d70-c3a8-4883-95c0-85e1becc5400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bankName&quot;)</value>
      <webElementGuid>5d6d137c-fc9b-40a0-8b5f-4d98d6a1e4aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bankName']</value>
      <webElementGuid>28612dc6-0d7a-4366-a39a-f4f73b9defdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/bank-account/div/div/div/input</value>
      <webElementGuid>1b7933f7-9d46-4190-9ffe-800d896ad62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bank-account/div/div/div/input</value>
      <webElementGuid>60cf98da-b750-4c83-8a75-45a192d9369d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bankName']</value>
      <webElementGuid>99f58f67-2e42-4dd9-9ab8-2bb0afa0b4fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
