<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__arabicName</name>
   <tag></tag>
   <elementGuidId>6399df37-3d6f-4a20-a5b3-6d34246081ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='arabicName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#arabicName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef9961fa-ac06-4b0e-a7e6-715aabf22fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>arabicName</value>
      <webElementGuid>319ca9d0-e6da-42d2-b9ba-d22b43adf7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>arabicName</value>
      <webElementGuid>3de1da2e-d6a0-46ca-8b33-90e4dca4dca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>arabicName</value>
      <webElementGuid>5b843d5f-52fa-4185-9c86-b30091025735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>5d26d9c6-6c1e-4ce1-af3f-be811bcf8cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;arabicName&quot;)</value>
      <webElementGuid>ed7b74af-3c40-4ff7-b1fe-5adea3de2e01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='arabicName']</value>
      <webElementGuid>e70a593d-5604-4e55-a55c-84f6f51ab70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[3]/div/executive-management/div/div/div/input</value>
      <webElementGuid>92b67321-1ecb-4479-a153-57efbf0932a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//executive-management/div/div/div/input</value>
      <webElementGuid>dad30079-4dc0-4855-9848-7111dfedecfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'arabicName']</value>
      <webElementGuid>b8bd9621-c400-4860-96aa-d1c195d450d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
