<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__licenseDurationType</name>
   <tag></tag>
   <elementGuidId>4472bdfe-23c9-435f-8ad8-22db5dd07306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='licenseDurationType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ng-input > #licenseDurationType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0a7fde3-e600-4be9-85c6-bcc67d116e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>44dc21ef-732e-4068-bca8-64be325bfdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6dd91c5-96bd-4107-8a47-6b0649be07d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>981f84a0-4cbb-445e-a5b4-c78d075f6f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f0e4c6de-0764-4fad-a4d4-bc9d4eee4fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a390f87e-4672-47d1-938c-c4ec2546e855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>licenseDurationType</value>
      <webElementGuid>ec1a8e5b-41bb-4d54-8eaf-99a348ae9a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-list-1-content&quot;)/tab[@class=&quot;ng-tns-c34-293 ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c34-293 ng-star-inserted&quot;]/div[@class=&quot;ng-invalid ng-star-inserted ng-untouched ng-pristine&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-12 col-md-4&quot;]/div[@class=&quot;d-flex align-items-center justify-content-start gap-2&quot;]/div[@class=&quot;mb-4 ng-select-wrapper flex-grow-1&quot;]/ng-select[@id=&quot;licenseDurationType&quot;]/div[@class=&quot;ng-select-container&quot;]/div[@class=&quot;ng-value-container&quot;]/div[@class=&quot;ng-input&quot;]/input[@id=&quot;licenseDurationType&quot;]</value>
      <webElementGuid>8094fdfb-b4d4-4653-8bd6-70262a1a77a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='licenseDurationType']</value>
      <webElementGuid>782529b3-1112-4dad-b6c2-e9097c85e3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-select[@id='licenseDurationType']/div/div/div[2]/input</value>
      <webElementGuid>58a3e38f-14dd-4b2d-b441-129add529d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ng-select/div/div/div[2]/input</value>
      <webElementGuid>444ddd9a-ea65-4ee1-8115-8fb40b7524ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'licenseDurationType']</value>
      <webElementGuid>5ecae130-4ede-4a0f-91c6-48e14abe62dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
