<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__iBan</name>
   <tag></tag>
   <elementGuidId>813374b4-b82d-4807-9e6a-f9305a3cab85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='iBan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iBan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d8348ed-b976-49fe-a7a3-0dca476cd61f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iBan</value>
      <webElementGuid>60a8d5a5-2b00-4ad4-ae10-56607718a360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>iBan</value>
      <webElementGuid>014abd91-fc6f-4e50-886c-ed22a277e71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>iBan</value>
      <webElementGuid>e487fa97-0285-44e1-8820-25acda021ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>50bf3bb6-9e83-4451-8ef5-aa17206397cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iBan&quot;)</value>
      <webElementGuid>7fd42fc7-976d-44c0-aa3c-1b8be819c95d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='iBan']</value>
      <webElementGuid>010f0b9d-db85-49d3-9ed0-b696d91fecf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/bank-account/div/div/div[3]/input</value>
      <webElementGuid>5291ffb0-8535-4956-b36c-a639bfe6b96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bank-account/div/div/div[3]/input</value>
      <webElementGuid>b6f6a31d-940b-4dc9-80ae-a41da6a66d8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'iBan']</value>
      <webElementGuid>76c932e2-c05c-4bd9-ae5c-30aff779d613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
