<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__accountNumber</name>
   <tag></tag>
   <elementGuidId>c662d2e5-4d37-4738-979f-78312917426b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accountNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accountNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51f0f083-4bbc-4f6d-9e5b-ce0da43dc406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accountNumber</value>
      <webElementGuid>cb36148f-eb30-410e-9781-5b5239e41e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validationclasses</name>
      <type>Main</type>
      <value>accountNumber</value>
      <webElementGuid>c1ff03e7-f7ae-49c0-a635-3e973073558e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>accountNumber</value>
      <webElementGuid>6a210655-fda8-4c67-963b-149d13c234ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6bdd0243-a415-4320-a1e3-fb76ed2b105b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountNumber&quot;)</value>
      <webElementGuid>b5f52e49-6c80-49cf-ac06-fcfc1eb96784</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accountNumber']</value>
      <webElementGuid>605ef76d-d739-4a44-998f-00b50f27decd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-list-1-content']/tab[2]/div/bank-account/div/div/div[2]/input</value>
      <webElementGuid>31dca8ad-1699-4dea-bff9-3f16482fb928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bank-account/div/div/div[2]/input</value>
      <webElementGuid>89c34e19-0e4a-4e97-8f98-6b81cff12c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'accountNumber']</value>
      <webElementGuid>49939b13-7a2d-4a62-8e7c-f742f9750d41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
