<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login Arabic UI</name>
   <tag></tag>
   <elementGuidId>9428a7a9-cf55-46d2-81bf-7adf0961c7d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.shadow-sm.btn.d-block.btn-primary.flex-fill</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='login-card']/div/form/div/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc7bf99e-b119-4a21-b7a1-c1df38746eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>12d4f9d0-35fb-43ae-b91c-5750cc3e2d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shadow-sm btn d-block btn-primary flex-fill</value>
      <webElementGuid>ccf58209-3f41-4c08-93ab-c9c5304ce60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>تسجيل دخول</value>
      <webElementGuid>63bf763a-e4df-4d41-9e17-f467b63b6083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-card&quot;)/div[@class=&quot;d-flex flex-column align-items-center justify-content-center&quot;]/form[@class=&quot;mt-2 ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;d-flex flex-column&quot;]/div[@class=&quot;d-flex flex-row mt-3 mb-3&quot;]/button[@class=&quot;shadow-sm btn d-block btn-primary flex-fill&quot;]</value>
      <webElementGuid>e4f56c07-2ab5-4b1d-87ae-d3979625336e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-card']/div/form/div/div[3]/button</value>
      <webElementGuid>e992d931-b268-4222-b585-f1d2a007fcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='كلمة المرور'])[1]/following::button[2]</value>
      <webElementGuid>cbb405e4-e65e-40ad-a13e-5118993a5549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='أسم المستخدم'])[1]/following::button[2]</value>
      <webElementGuid>c6c79975-e106-44f0-b733-8a2752c75c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/preceding::button[1]</value>
      <webElementGuid>096d4a28-b030-4600-acfb-81ac6222de6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v1.5.0-rc#2'])[1]/preceding::button[1]</value>
      <webElementGuid>a4786082-8d58-4529-b7a4-3a9c5fbeeeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='تسجيل دخول']/parent::*</value>
      <webElementGuid>78f8f738-508e-43f9-bf2c-c8817b91c24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>f64200e8-e2b2-4040-9561-4024a13478bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'تسجيل دخول' or . = 'تسجيل دخول')]</value>
      <webElementGuid>b52256ab-fb73-4242-ab84-5b63716e9533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
