<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_Arabic UI</name>
   <tag></tag>
   <elementGuidId>c245153c-27c7-47a0-bb09-8cb8c734613d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aaaac650-ae86-495a-81ce-d951f4235a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>userPassword</value>
      <webElementGuid>b82f68e9-fe44-4b88-a328-451ce74b1612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>00222e21-757e-41ba-b84d-c41690f96d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userPassword</value>
      <webElementGuid>ef2951d1-d713-44da-93fa-175bf5cf99ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-right ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>c043a8ef-144d-4bd7-a6e0-d9c1a422ca08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>أدخل كلمة المرور</value>
      <webElementGuid>5175af99-202c-40e0-a84c-676f206b588c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d1328006-9fd7-4d6b-9a98-f25b336a0faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userPassword&quot;)</value>
      <webElementGuid>c4f286b0-2528-45cf-9929-7da2e8bddedb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userPassword']</value>
      <webElementGuid>832371a4-078d-4dc5-a7cd-dfab37e29c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-card']/div/form/div/div[2]/div/input</value>
      <webElementGuid>56d53efc-6e88-45de-8237-2d2b9bdcb6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c7f6e72b-4de1-46b4-8523-c67128305f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'userPassword' and @placeholder = 'أدخل كلمة المرور' and @type = 'password']</value>
      <webElementGuid>107756f9-7389-4b18-89d6-a4a41a33accc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
