<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Password_Arabic UI</name>
   <tag></tag>
   <elementGuidId>584ac0e1-0a05-4202-b6fa-faa39fc4126f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9151dde5-b434-4748-9b2d-44539f730735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>userPassword</value>
      <webElementGuid>16aa9c8b-c088-489f-9e00-66094c03031f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>b2cf31a2-5a21-47da-8a0b-5532c0a70736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userPassword</value>
      <webElementGuid>1fcbb8fb-dc5f-4aa2-bca7-b483d43d0f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control p-right ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>945f6eb9-58ce-427d-95d0-119f9799904e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>أدخل كلمة المرور</value>
      <webElementGuid>4e4586b5-5d42-4311-b12c-13e3ff926853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>dd6cc212-5ce7-4506-9c04-ae8673be6bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userPassword&quot;)</value>
      <webElementGuid>92c1b13d-740c-49a3-817f-d2157f7e5862</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userPassword']</value>
      <webElementGuid>74bc44bc-43c9-47b5-bb92-44912dcb308b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='login-card']/div/form/div/div[2]/div/input</value>
      <webElementGuid>da290508-df8a-4f49-ae78-8ed7dc8dd8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>f41fc111-a5c3-497e-9e5a-94ca2445d1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'userPassword' and @placeholder = 'أدخل كلمة المرور' and @type = 'password']</value>
      <webElementGuid>45a8d021-df2f-4328-adde-81b5d7e56a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
